# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analyzer_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(569, 262)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(480, 10, 51, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 471, 211))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 20, 451, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_31 = QtWidgets.QLabel(self.groupBox_2)
        self.label_31.setGeometry(QtCore.QRect(140, 10, 61, 61))
        self.label_31.setWordWrap(True)
        self.label_31.setObjectName("label_31")
        self.lineEdit_number_of_peaks_to_search = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_number_of_peaks_to_search.setGeometry(QtCore.QRect(200, 20, 31, 31))
        self.lineEdit_number_of_peaks_to_search.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_number_of_peaks_to_search.setObjectName("lineEdit_number_of_peaks_to_search")
        self.lineEdit_min_peak_distance = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_min_peak_distance.setGeometry(QtCore.QRect(410, 20, 31, 31))
        self.lineEdit_min_peak_distance.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_min_peak_distance.setObjectName("lineEdit_min_peak_distance")
        self.label_32 = QtWidgets.QLabel(self.groupBox_2)
        self.label_32.setGeometry(QtCore.QRect(350, 10, 61, 61))
        self.label_32.setWordWrap(True)
        self.label_32.setObjectName("label_32")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(260, 10, 41, 61))
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName("label_17")
        self.lineEdit_min_peak_level = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_min_peak_level.setGeometry(QtCore.QRect(300, 20, 31, 31))
        self.lineEdit_min_peak_level.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_min_peak_level.setObjectName("lineEdit_min_peak_level")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(30, 40, 41, 31))
        self.label_16.setWordWrap(True)
        self.label_16.setObjectName("label_16")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(30, 10, 41, 31))
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.lineEdit_min_wave = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_min_wave.setGeometry(QtCore.QRect(80, 20, 41, 20))
        self.lineEdit_min_wave.setObjectName("lineEdit_min_wave")
        self.lineEdit_max_wave = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_max_wave.setGeometry(QtCore.QRect(80, 50, 41, 20))
        self.lineEdit_max_wave.setObjectName("lineEdit_max_wave")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 119, 451, 91))
        self.groupBox_3.setObjectName("groupBox_3")
        self.checkBox_plot_results_separately = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_plot_results_separately.setGeometry(QtCore.QRect(20, 20, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.checkBox_plot_results_separately.setFont(font)
        self.checkBox_plot_results_separately.setWhatsThis("")
        self.checkBox_plot_results_separately.setTristate(False)
        self.checkBox_plot_results_separately.setObjectName("checkBox_plot_results_separately")
        self.checkBox_find_widths = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_find_widths.setGeometry(QtCore.QRect(130, 20, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.checkBox_find_widths.setFont(font)
        self.checkBox_find_widths.setWhatsThis("")
        self.checkBox_find_widths.setTristate(False)
        self.checkBox_find_widths.setObjectName("checkBox_find_widths")
        self.lineEdit_N_points_for_fitting = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_N_points_for_fitting.setGeometry(QtCore.QRect(330, 20, 21, 21))
        self.lineEdit_N_points_for_fitting.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_N_points_for_fitting.setObjectName("lineEdit_N_points_for_fitting")
        self.label_33 = QtWidgets.QLabel(self.groupBox_3)
        self.label_33.setGeometry(QtCore.QRect(250, 20, 81, 21))
        self.label_33.setWordWrap(True)
        self.label_33.setObjectName("label_33")
        self.checkBox_iterate_different_N_points = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_iterate_different_N_points.setGeometry(QtCore.QRect(190, 58, 16, 21))
        self.checkBox_iterate_different_N_points.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.checkBox_iterate_different_N_points.setText("")
        self.checkBox_iterate_different_N_points.setAutoRepeat(False)
        self.checkBox_iterate_different_N_points.setAutoRepeatInterval(-5)
        self.checkBox_iterate_different_N_points.setObjectName("checkBox_iterate_different_N_points")
        self.label_34 = QtWidgets.QLabel(self.groupBox_3)
        self.label_34.setGeometry(QtCore.QRect(300, 60, 101, 21))
        self.label_34.setWordWrap(True)
        self.label_34.setObjectName("label_34")
        self.lineEdit_max_N_points_for_fitting = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_max_N_points_for_fitting.setEnabled(False)
        self.lineEdit_max_N_points_for_fitting.setGeometry(QtCore.QRect(400, 60, 41, 21))
        self.lineEdit_max_N_points_for_fitting.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_max_N_points_for_fitting.setObjectName("lineEdit_max_N_points_for_fitting")
        self.label_35 = QtWidgets.QLabel(self.groupBox_3)
        self.label_35.setGeometry(QtCore.QRect(210, 54, 81, 31))
        self.label_35.setWordWrap(True)
        self.label_35.setObjectName("label_35")
        self.label_35.raise_()
        self.checkBox_plot_results_separately.raise_()
        self.checkBox_find_widths.raise_()
        self.lineEdit_N_points_for_fitting.raise_()
        self.label_33.raise_()
        self.checkBox_iterate_different_N_points.raise_()
        self.label_34.raise_()
        self.lineEdit_max_N_points_for_fitting.raise_()

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.checkBox_iterate_different_N_points.clicked['bool'].connect(self.lineEdit_N_points_for_fitting.setDisabled)
        self.checkBox_iterate_different_N_points.clicked['bool'].connect(self.lineEdit_max_N_points_for_fitting.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Analyzer options"))
        self.groupBox_2.setTitle(_translate("Dialog", "Main params"))
        self.label_31.setText(_translate("Dialog", "<html><head/><body><p>Number of peaks to be find</p></body></html>"))
        self.lineEdit_number_of_peaks_to_search.setText(_translate("Dialog", "1"))
        self.lineEdit_min_peak_distance.setText(_translate("Dialog", "60"))
        self.label_32.setText(_translate("Dialog", "<html><head/><body><p>Distance between peaks</p></body></html>"))
        self.label_17.setText(_translate("Dialog", "<html><head/><body><p>Peak height, dB</p></body></html>"))
        self.lineEdit_min_peak_level.setText(_translate("Dialog", "3"))
        self.label_16.setText(_translate("Dialog", "<html><head/><body><p>λ<span style=\" vertical-align:sub;\">max</span>, nm</p></body></html>"))
        self.label_15.setText(_translate("Dialog", "<html><head/><body><p>λ<span style=\" vertical-align:sub;\">min</span>, nm</p></body></html>"))
        self.lineEdit_min_wave.setText(_translate("Dialog", "1530"))
        self.lineEdit_max_wave.setText(_translate("Dialog", "1590"))
        self.groupBox_3.setTitle(_translate("Dialog", "Andvanced"))
        self.checkBox_plot_results_separately.setText(_translate("Dialog", "Plot separately"))
        self.checkBox_find_widths.setText(_translate("Dialog", "find widths"))
        self.lineEdit_N_points_for_fitting.setText(_translate("Dialog", "0"))
        self.label_33.setText(_translate("Dialog", "<html><head/><body><p>N_points for fit</p></body></html>"))
        self.label_34.setText(_translate("Dialog", "<html><head/><body><p>max N_points for fit</p></body></html>"))
        self.lineEdit_max_N_points_for_fitting.setText(_translate("Dialog", "100"))
        self.label_35.setText(_translate("Dialog", "<html><head/><body><p>iterating over N_points</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

