# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Александр\Desktop\work\Github\ScanLoop\Windows\UIs\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1115, 728)
        MainWindow.setMinimumSize(QtCore.QSize(730, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 10000))
        MainWindow.setAcceptDrops(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(255)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setBaseSize(QtCore.QSize(-25536, 0))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setEnabled(True)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1095, 667))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_11 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_11.sizePolicy().hasHeightForWidth())
        self.groupBox_11.setSizePolicy(sizePolicy)
        self.groupBox_11.setMinimumSize(QtCore.QSize(300, 50))
        self.groupBox_11.setMaximumSize(QtCore.QSize(300, 50))
        self.groupBox_11.setObjectName("groupBox_11")
        self.EditLine_FilterLowFreqEdge = QtWidgets.QLineEdit(self.groupBox_11)
        self.EditLine_FilterLowFreqEdge.setGeometry(QtCore.QRect(87, 23, 70, 17))
        self.EditLine_FilterLowFreqEdge.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.EditLine_FilterLowFreqEdge.setObjectName("EditLine_FilterLowFreqEdge")
        self.EditLine_FilterHighFreqEdge = QtWidgets.QLineEdit(self.groupBox_11)
        self.EditLine_FilterHighFreqEdge.setGeometry(QtCore.QRect(163, 23, 71, 17))
        self.EditLine_FilterHighFreqEdge.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.EditLine_FilterHighFreqEdge.setObjectName("EditLine_FilterHighFreqEdge")
        self.CheckBox_ApplyFFTFilter = QtWidgets.QCheckBox(self.groupBox_11)
        self.CheckBox_ApplyFFTFilter.setGeometry(QtCore.QRect(240, 23, 50, 17))
        self.CheckBox_ApplyFFTFilter.setObjectName("CheckBox_ApplyFFTFilter")
        self.EditLine_FilterPointsToCut = QtWidgets.QLineEdit(self.groupBox_11)
        self.EditLine_FilterPointsToCut.setGeometry(QtCore.QRect(10, 23, 71, 17))
        self.EditLine_FilterPointsToCut.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.EditLine_FilterPointsToCut.setObjectName("EditLine_FilterPointsToCut")
        self.gridLayout_4.addWidget(self.groupBox_11, 1, 3, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setMinimumSize(QtCore.QSize(300, 50))
        self.groupBox_9.setMaximumSize(QtCore.QSize(450, 50))
        self.groupBox_9.setObjectName("groupBox_9")
        self.EditLine_StartWavelength = QtWidgets.QLineEdit(self.groupBox_9)
        self.EditLine_StartWavelength.setGeometry(QtCore.QRect(10, 20, 131, 20))
        self.EditLine_StartWavelength.setMaxLength(12)
        self.EditLine_StartWavelength.setObjectName("EditLine_StartWavelength")
        self.EditLine_StopWavelength = QtWidgets.QLineEdit(self.groupBox_9)
        self.EditLine_StopWavelength.setGeometry(QtCore.QRect(150, 20, 131, 20))
        self.EditLine_StopWavelength.setMaxLength(12)
        self.EditLine_StopWavelength.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.EditLine_StopWavelength.setObjectName("EditLine_StopWavelength")
        self.pushButton_getRange = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_getRange.setGeometry(QtCore.QRect(290, 20, 91, 21))
        self.pushButton_getRange.setObjectName("pushButton_getRange")
        self.CheckBox_FreezeSpectrum = QtWidgets.QCheckBox(self.groupBox_9)
        self.CheckBox_FreezeSpectrum.setGeometry(QtCore.QRect(390, 20, 56, 17))
        self.CheckBox_FreezeSpectrum.setObjectName("CheckBox_FreezeSpectrum")
        self.gridLayout_4.addWidget(self.groupBox_9, 1, 2, 1, 1)
        self.File_work = QtWidgets.QToolBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.File_work.sizePolicy().hasHeightForWidth())
        self.File_work.setSizePolicy(sizePolicy)
        self.File_work.setMinimumSize(QtCore.QSize(300, 0))
        self.File_work.setMaximumSize(QtCore.QSize(300, 16777215))
        self.File_work.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.File_work.setObjectName("File_work")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 300, 541))
        self.page.setObjectName("page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.page)
        self.groupBox_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_StagesConnect = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_StagesConnect.setGeometry(QtCore.QRect(110, 23, 91, 23))
        self.pushButton_StagesConnect.setCheckable(True)
        self.pushButton_StagesConnect.setObjectName("pushButton_StagesConnect")
        self.pushButton_OSA_connect = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_OSA_connect.setGeometry(QtCore.QRect(110, 110, 91, 23))
        self.pushButton_OSA_connect.setCheckable(True)
        self.pushButton_OSA_connect.setObjectName("pushButton_OSA_connect")
        self.pushButton_scope_connect = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_scope_connect.setGeometry(QtCore.QRect(110, 52, 91, 23))
        self.pushButton_scope_connect.setCheckable(False)
        self.pushButton_scope_connect.setObjectName("pushButton_scope_connect")
        self.pushButton_laser_connect = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_laser_connect.setGeometry(QtCore.QRect(110, 81, 91, 23))
        self.pushButton_laser_connect.setObjectName("pushButton_laser_connect")
        self.comboBox_Type_of_OSA = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_Type_of_OSA.setGeometry(QtCore.QRect(10, 110, 91, 20))
        self.comboBox_Type_of_OSA.setObjectName("comboBox_Type_of_OSA")
        self.comboBox_Type_of_OSA.addItem("")
        self.comboBox_Type_of_OSA.addItem("")
        self.comboBox_Type_of_OSA.addItem("")
        self.comboBox_Type_of_OSA.addItem("")
        self.comboBox_Type_of_Stages = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_Type_of_Stages.setGeometry(QtCore.QRect(10, 24, 91, 20))
        self.comboBox_Type_of_Stages.setObjectName("comboBox_Type_of_Stages")
        self.comboBox_Type_of_Stages.addItem("")
        self.comboBox_Type_of_Stages.addItem("")
        self.lineEdit_laser_COMport = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_laser_COMport.setGeometry(QtCore.QRect(80, 82, 21, 20))
        self.lineEdit_laser_COMport.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_laser_COMport.setObjectName("lineEdit_laser_COMport")
        self.label_24 = QtWidgets.QLabel(self.groupBox_3)
        self.label_24.setGeometry(QtCore.QRect(10, 82, 61, 20))
        self.label_24.setObjectName("label_24")
        self.pushButton_zeroing_stages = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_zeroing_stages.setGeometry(QtCore.QRect(210, 23, 61, 21))
        self.pushButton_zeroing_stages.setObjectName("pushButton_zeroing_stages")
        self.groupBox_features = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_features.setEnabled(True)
        self.groupBox_features.setGeometry(QtCore.QRect(10, 150, 251, 61))
        self.groupBox_features.setObjectName("groupBox_features")
        self.comboBox_APEX_mode = QtWidgets.QComboBox(self.groupBox_features)
        self.comboBox_APEX_mode.setEnabled(False)
        self.comboBox_APEX_mode.setGeometry(QtCore.QRect(120, 20, 91, 21))
        self.comboBox_APEX_mode.setObjectName("comboBox_APEX_mode")
        self.comboBox_APEX_mode.addItem("")
        self.comboBox_APEX_mode.addItem("")
        self.comboBox_Luna_mode = QtWidgets.QComboBox(self.groupBox_features)
        self.comboBox_Luna_mode.setEnabled(True)
        self.comboBox_Luna_mode.setGeometry(QtCore.QRect(120, 20, 121, 22))
        self.comboBox_Luna_mode.setObjectName("comboBox_Luna_mode")
        self.comboBox_Luna_mode.addItem("")
        self.comboBox_Luna_mode.addItem("")
        self.label_Luna_mode = QtWidgets.QLabel(self.groupBox_features)
        self.label_Luna_mode.setEnabled(True)
        self.label_Luna_mode.setGeometry(QtCore.QRect(10, 20, 91, 20))
        self.label_Luna_mode.setObjectName("label_Luna_mode")
        self.label_29 = QtWidgets.QLabel(self.groupBox_features)
        self.label_29.setEnabled(True)
        self.label_29.setGeometry(QtCore.QRect(10, 20, 81, 21))
        self.label_29.setObjectName("label_29")
        self.groupBox_features.raise_()
        self.pushButton_StagesConnect.raise_()
        self.pushButton_OSA_connect.raise_()
        self.pushButton_scope_connect.raise_()
        self.pushButton_laser_connect.raise_()
        self.comboBox_Type_of_OSA.raise_()
        self.comboBox_Type_of_Stages.raise_()
        self.lineEdit_laser_COMport.raise_()
        self.label_24.raise_()
        self.pushButton_zeroing_stages.raise_()
        self.verticalLayout.addWidget(self.groupBox_3)
        self.File_work.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 283, 700))
        self.page_2.setMinimumSize(QtCore.QSize(0, 700))
        self.page_2.setObjectName("page_2")
        self.tabWidget_instruments = QtWidgets.QTabWidget(self.page_2)
        self.tabWidget_instruments.setEnabled(False)
        self.tabWidget_instruments.setGeometry(QtCore.QRect(0, 220, 291, 121))
        self.tabWidget_instruments.setObjectName("tabWidget_instruments")
        self.groupBox_OSA_control = QtWidgets.QWidget()
        self.groupBox_OSA_control.setObjectName("groupBox_OSA_control")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_OSA_control)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_OSA_control)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBox_interrogatorChannel = QtWidgets.QComboBox(self.groupBox_OSA_control)
        self.comboBox_interrogatorChannel.setObjectName("comboBox_interrogatorChannel")
        self.comboBox_interrogatorChannel.addItem("")
        self.comboBox_interrogatorChannel.addItem("")
        self.comboBox_interrogatorChannel.addItem("")
        self.comboBox_interrogatorChannel.addItem("")
        self.comboBox_interrogatorChannel.addItem("")
        self.comboBox_interrogatorChannel.addItem("")
        self.comboBox_interrogatorChannel.addItem("")
        self.comboBox_interrogatorChannel.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_interrogatorChannel)
        self.pushButton_OSA_Acquire = QtWidgets.QPushButton(self.groupBox_OSA_control)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_OSA_Acquire.setFont(font)
        self.pushButton_OSA_Acquire.setObjectName("pushButton_OSA_Acquire")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton_OSA_Acquire)
        self.pushButton_OSA_AcquireRep = QtWidgets.QPushButton(self.groupBox_OSA_control)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_OSA_AcquireRep.setFont(font)
        self.pushButton_OSA_AcquireRep.setCheckable(True)
        self.pushButton_OSA_AcquireRep.setObjectName("pushButton_OSA_AcquireRep")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pushButton_OSA_AcquireRep)
        self.checkBox_HighRes = QtWidgets.QCheckBox(self.groupBox_OSA_control)
        self.checkBox_HighRes.setCheckable(True)
        self.checkBox_HighRes.setObjectName("checkBox_HighRes")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.checkBox_HighRes)
        self.pushButton_OSA_AcquireAll = QtWidgets.QPushButton(self.groupBox_OSA_control)
        self.pushButton_OSA_AcquireAll.setObjectName("pushButton_OSA_AcquireAll")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButton_OSA_AcquireAll)
        self.tabWidget_instruments.addTab(self.groupBox_OSA_control, "")
        self.groupBox_scope_control = QtWidgets.QWidget()
        self.groupBox_scope_control.setObjectName("groupBox_scope_control")
        self.pushButton_scope_repeat = QtWidgets.QPushButton(self.groupBox_scope_control)
        self.pushButton_scope_repeat.setGeometry(QtCore.QRect(140, 50, 93, 28))
        self.pushButton_scope_repeat.setCheckable(True)
        self.pushButton_scope_repeat.setObjectName("pushButton_scope_repeat")
        self.pushButton_scope_single = QtWidgets.QPushButton(self.groupBox_scope_control)
        self.pushButton_scope_single.setGeometry(QtCore.QRect(10, 50, 93, 28))
        self.pushButton_scope_single.setObjectName("pushButton_scope_single")
        self.label_10 = QtWidgets.QLabel(self.groupBox_scope_control)
        self.label_10.setGeometry(QtCore.QRect(20, 15, 47, 10))
        self.label_10.setObjectName("label_10")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_scope_control)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 10, 159, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_ScopeCh1 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_ScopeCh1.setObjectName("checkBox_ScopeCh1")
        self.horizontalLayout_3.addWidget(self.checkBox_ScopeCh1)
        self.checkBox_ScopeCh2 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_ScopeCh2.setObjectName("checkBox_ScopeCh2")
        self.horizontalLayout_3.addWidget(self.checkBox_ScopeCh2)
        self.checkBox_ScopeCh3 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_ScopeCh3.setObjectName("checkBox_ScopeCh3")
        self.horizontalLayout_3.addWidget(self.checkBox_ScopeCh3)
        self.checkBox_ScopeCh4 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_ScopeCh4.setObjectName("checkBox_ScopeCh4")
        self.horizontalLayout_3.addWidget(self.checkBox_ScopeCh4)
        self.tabWidget_instruments.addTab(self.groupBox_scope_control, "")
        self.groupBox_stand = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_stand.setEnabled(False)
        self.groupBox_stand.setGeometry(QtCore.QRect(0, 0, 271, 211))
        self.groupBox_stand.setObjectName("groupBox_stand")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_stand)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_MoveMinusX = QtWidgets.QPushButton(self.groupBox_stand)
        self.pushButton_MoveMinusX.setObjectName("pushButton_MoveMinusX")
        self.gridLayout.addWidget(self.pushButton_MoveMinusX, 2, 0, 1, 1)
        self.pushButton_MovePlusY = QtWidgets.QPushButton(self.groupBox_stand)
        self.pushButton_MovePlusY.setObjectName("pushButton_MovePlusY")
        self.gridLayout.addWidget(self.pushButton_MovePlusY, 1, 1, 1, 1)
        self.pushButton_MoveMinusZ = QtWidgets.QPushButton(self.groupBox_stand)
        self.pushButton_MoveMinusZ.setObjectName("pushButton_MoveMinusZ")
        self.gridLayout.addWidget(self.pushButton_MoveMinusZ, 2, 2, 1, 1)
        self.lineEdit_StepZ = QtWidgets.QLineEdit(self.groupBox_stand)
        self.lineEdit_StepZ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_StepZ.setObjectName("lineEdit_StepZ")
        self.gridLayout.addWidget(self.lineEdit_StepZ, 0, 2, 1, 1)
        self.pushButton_MovePlusZ = QtWidgets.QPushButton(self.groupBox_stand)
        self.pushButton_MovePlusZ.setObjectName("pushButton_MovePlusZ")
        self.gridLayout.addWidget(self.pushButton_MovePlusZ, 1, 2, 1, 1)
        self.pushButton_MovePlusX = QtWidgets.QPushButton(self.groupBox_stand)
        self.pushButton_MovePlusX.setObjectName("pushButton_MovePlusX")
        self.gridLayout.addWidget(self.pushButton_MovePlusX, 1, 0, 1, 1)
        self.lineEdit_StepY = QtWidgets.QLineEdit(self.groupBox_stand)
        self.lineEdit_StepY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_StepY.setObjectName("lineEdit_StepY")
        self.gridLayout.addWidget(self.lineEdit_StepY, 0, 1, 1, 1)
        self.pushButton_MoveMinusY = QtWidgets.QPushButton(self.groupBox_stand)
        self.pushButton_MoveMinusY.setObjectName("pushButton_MoveMinusY")
        self.gridLayout.addWidget(self.pushButton_MoveMinusY, 2, 1, 1, 1)
        self.lineEdit_StepX = QtWidgets.QLineEdit(self.groupBox_stand)
        self.lineEdit_StepX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_StepX.setObjectName("lineEdit_StepX")
        self.gridLayout.addWidget(self.lineEdit_StepX, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_stand)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_PositionZ = QtWidgets.QLabel(self.groupBox_6)
        self.label_PositionZ.setGeometry(QtCore.QRect(200, 30, 51, 20))
        self.label_PositionZ.setAlignment(QtCore.Qt.AlignCenter)
        self.label_PositionZ.setObjectName("label_PositionZ")
        self.label_AbsPositionX = QtWidgets.QLabel(self.groupBox_6)
        self.label_AbsPositionX.setGeometry(QtCore.QRect(5, 70, 61, 20))
        self.label_AbsPositionX.setAlignment(QtCore.Qt.AlignCenter)
        self.label_AbsPositionX.setObjectName("label_AbsPositionX")
        self.pushButton_zeroingPositions = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_zeroingPositions.setGeometry(QtCore.QRect(90, 10, 106, 20))
        self.pushButton_zeroingPositions.setObjectName("pushButton_zeroingPositions")
        self.label_PositionY = QtWidgets.QLabel(self.groupBox_6)
        self.label_PositionY.setGeometry(QtCore.QRect(110, 30, 51, 20))
        self.label_PositionY.setAlignment(QtCore.Qt.AlignCenter)
        self.label_PositionY.setObjectName("label_PositionY")
        self.label_PositionX = QtWidgets.QLabel(self.groupBox_6)
        self.label_PositionX.setGeometry(QtCore.QRect(10, 30, 51, 20))
        self.label_PositionX.setAlignment(QtCore.Qt.AlignCenter)
        self.label_PositionX.setObjectName("label_PositionX")
        self.label_AbsPositionY = QtWidgets.QLabel(self.groupBox_6)
        self.label_AbsPositionY.setGeometry(QtCore.QRect(110, 70, 50, 16))
        self.label_AbsPositionY.setAlignment(QtCore.Qt.AlignCenter)
        self.label_AbsPositionY.setObjectName("label_AbsPositionY")
        self.label_AbsPositionZ = QtWidgets.QLabel(self.groupBox_6)
        self.label_AbsPositionZ.setGeometry(QtCore.QRect(198, 70, 55, 16))
        self.label_AbsPositionZ.setAlignment(QtCore.Qt.AlignCenter)
        self.label_AbsPositionZ.setObjectName("label_AbsPositionZ")
        self.label_11 = QtWidgets.QLabel(self.groupBox_6)
        self.label_11.setGeometry(QtCore.QRect(20, 13, 50, 13))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_6)
        self.label_12.setGeometry(QtCore.QRect(20, 53, 47, 13))
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.groupBox_6, 3, 0, 1, 3)
        self.groupBox_save_data = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_save_data.setGeometry(QtCore.QRect(0, 560, 291, 141))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_save_data.sizePolicy().hasHeightForWidth())
        self.groupBox_save_data.setSizePolicy(sizePolicy)
        self.groupBox_save_data.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.groupBox_save_data.setObjectName("groupBox_save_data")
        self.pushButton_LoadParameters = QtWidgets.QPushButton(self.groupBox_save_data)
        self.pushButton_LoadParameters.setGeometry(QtCore.QRect(100, 23, 171, 21))
        self.pushButton_LoadParameters.setObjectName("pushButton_LoadParameters")
        self.EditLine_saveSpectrumName = QtWidgets.QLineEdit(self.groupBox_save_data)
        self.EditLine_saveSpectrumName.setGeometry(QtCore.QRect(100, 52, 171, 16))
        self.EditLine_saveSpectrumName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.EditLine_saveSpectrumName.setObjectName("EditLine_saveSpectrumName")
        self.pushButton_save_data = QtWidgets.QPushButton(self.groupBox_save_data)
        self.pushButton_save_data.setGeometry(QtCore.QRect(10, 50, 84, 21))
        self.pushButton_save_data.setObjectName("pushButton_save_data")
        self.pushButton_SaveParameters = QtWidgets.QPushButton(self.groupBox_save_data)
        self.pushButton_SaveParameters.setGeometry(QtCore.QRect(10, 23, 84, 21))
        self.pushButton_SaveParameters.setObjectName("pushButton_SaveParameters")
        self.pushButton_processTDData = QtWidgets.QPushButton(self.groupBox_save_data)
        self.pushButton_processTDData.setGeometry(QtCore.QRect(10, 110, 81, 21))
        self.pushButton_processTDData.setObjectName("pushButton_processTDData")
        self.checkBox_IsShiftingWhileProcessing = QtWidgets.QCheckBox(self.groupBox_save_data)
        self.checkBox_IsShiftingWhileProcessing.setGeometry(QtCore.QRect(150, 80, 81, 16))
        self.checkBox_IsShiftingWhileProcessing.setObjectName("checkBox_IsShiftingWhileProcessing")
        self.checkBox_IsAveragingWhileProcessing = QtWidgets.QCheckBox(self.groupBox_save_data)
        self.checkBox_IsAveragingWhileProcessing.setGeometry(QtCore.QRect(230, 81, 61, 16))
        self.checkBox_IsAveragingWhileProcessing.setObjectName("checkBox_IsAveragingWhileProcessing")
        self.pushButton_processSpectralData = QtWidgets.QPushButton(self.groupBox_save_data)
        self.pushButton_processSpectralData.setGeometry(QtCore.QRect(10, 77, 81, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_processSpectralData.setFont(font)
        self.pushButton_processSpectralData.setObjectName("pushButton_processSpectralData")
        self.comboBox_TD_channel_to_plot = QtWidgets.QComboBox(self.groupBox_save_data)
        self.comboBox_TD_channel_to_plot.setGeometry(QtCore.QRect(100, 110, 32, 20))
        self.comboBox_TD_channel_to_plot.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_TD_channel_to_plot.setObjectName("comboBox_TD_channel_to_plot")
        self.comboBox_TD_channel_to_plot.addItem("")
        self.comboBox_TD_channel_to_plot.addItem("")
        self.comboBox_TD_channel_to_plot.addItem("")
        self.comboBox_TD_channel_to_plot.addItem("")
        self.comboBox_axis_to_plot_along = QtWidgets.QComboBox(self.groupBox_save_data)
        self.comboBox_axis_to_plot_along.setGeometry(QtCore.QRect(100, 80, 36, 20))
        self.comboBox_axis_to_plot_along.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_axis_to_plot_along.setObjectName("comboBox_axis_to_plot_along")
        self.comboBox_axis_to_plot_along.addItem("")
        self.comboBox_axis_to_plot_along.addItem("")
        self.comboBox_axis_to_plot_along.addItem("")
        self.comboBox_axis_to_plot_along.addItem("")
        self.comboBox_axis_to_plot_along.addItem("")
        self.pushButton_plotSampleShape = QtWidgets.QPushButton(self.groupBox_save_data)
        self.pushButton_plotSampleShape.setGeometry(QtCore.QRect(160, 110, 111, 21))
        self.pushButton_plotSampleShape.setObjectName("pushButton_plotSampleShape")
        self.groupBox_Scanning = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_Scanning.setEnabled(False)
        self.groupBox_Scanning.setGeometry(QtCore.QRect(0, 340, 291, 211))
        self.groupBox_Scanning.setObjectName("groupBox_Scanning")
        self.label_4 = QtWidgets.QLabel(self.groupBox_Scanning)
        self.label_4.setGeometry(QtCore.QRect(10, 49, 64, 39))
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.pushButton_Scanning = QtWidgets.QPushButton(self.groupBox_Scanning)
        self.pushButton_Scanning.setGeometry(QtCore.QRect(10, 178, 271, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Scanning.setFont(font)
        self.pushButton_Scanning.setCheckable(True)
        self.pushButton_Scanning.setObjectName("pushButton_Scanning")
        self.label_5 = QtWidgets.QLabel(self.groupBox_Scanning)
        self.label_5.setGeometry(QtCore.QRect(80, 49, 63, 39))
        self.label_5.setScaledContents(False)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.lineEdit_CurrentFile = QtWidgets.QLineEdit(self.groupBox_Scanning)
        self.lineEdit_CurrentFile.setGeometry(QtCore.QRect(50, 150, 31, 20))
        self.lineEdit_CurrentFile.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_CurrentFile.setObjectName("lineEdit_CurrentFile")
        self.label_8 = QtWidgets.QLabel(self.groupBox_Scanning)
        self.label_8.setGeometry(QtCore.QRect(10, 152, 34, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_SearchingStep = QtWidgets.QLineEdit(self.groupBox_Scanning)
        self.lineEdit_SearchingStep.setGeometry(QtCore.QRect(80, 94, 63, 20))
        self.lineEdit_SearchingStep.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_SearchingStep.setObjectName("lineEdit_SearchingStep")
        self.label_7 = QtWidgets.QLabel(self.groupBox_Scanning)
        self.label_7.setGeometry(QtCore.QRect(218, 49, 63, 39))
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.lineEdit_ScanningStep = QtWidgets.QLineEdit(self.groupBox_Scanning)
        self.lineEdit_ScanningStep.setGeometry(QtCore.QRect(10, 94, 64, 20))
        self.lineEdit_ScanningStep.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_ScanningStep.setObjectName("lineEdit_ScanningStep")
        self.comboBox_ScanningType = QtWidgets.QComboBox(self.groupBox_Scanning)
        self.comboBox_ScanningType.setGeometry(QtCore.QRect(10, 23, 163, 20))
        self.comboBox_ScanningType.setObjectName("comboBox_ScanningType")
        self.comboBox_ScanningType.addItem("")
        self.comboBox_ScanningType.addItem("")
        self.comboBox_ScanningType.addItem("")
        self.comboBox_ScanningType.addItem("")
        self.lineEdit_LevelToDetectContact = QtWidgets.QLineEdit(self.groupBox_Scanning)
        self.lineEdit_LevelToDetectContact.setGeometry(QtCore.QRect(218, 94, 63, 20))
        self.lineEdit_LevelToDetectContact.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_LevelToDetectContact.setObjectName("lineEdit_LevelToDetectContact")
        self.lineEdit_StopFile = QtWidgets.QLineEdit(self.groupBox_Scanning)
        self.lineEdit_StopFile.setGeometry(QtCore.QRect(110, 150, 41, 20))
        self.lineEdit_StopFile.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_StopFile.setObjectName("lineEdit_StopFile")
        self.label_2 = QtWidgets.QLabel(self.groupBox_Scanning)
        self.label_2.setGeometry(QtCore.QRect(90, 152, 16, 16))
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_Scanning)
        self.label_6.setGeometry(QtCore.QRect(149, 49, 63, 39))
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.lineEdit_BackStep = QtWidgets.QLineEdit(self.groupBox_Scanning)
        self.lineEdit_BackStep.setGeometry(QtCore.QRect(149, 94, 63, 20))
        self.lineEdit_BackStep.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_BackStep.setObjectName("lineEdit_BackStep")
        self.checkBox_saveDifference = QtWidgets.QCheckBox(self.groupBox_Scanning)
        self.checkBox_saveDifference.setGeometry(QtCore.QRect(180, 151, 101, 17))
        self.checkBox_saveDifference.setObjectName("checkBox_saveDifference")
        self.checkBox_searchContact = QtWidgets.QCheckBox(self.groupBox_Scanning)
        self.checkBox_searchContact.setGeometry(QtCore.QRect(149, 124, 63, 17))
        self.checkBox_searchContact.setObjectName("checkBox_searchContact")
        self.checkBox_SqueezeSpan = QtWidgets.QCheckBox(self.groupBox_Scanning)
        self.checkBox_SqueezeSpan.setGeometry(QtCore.QRect(218, 124, 62, 17))
        self.checkBox_SqueezeSpan.setIconSize(QtCore.QSize(1, 1))
        self.checkBox_SqueezeSpan.setObjectName("checkBox_SqueezeSpan")
        self.checkBox_followPeak = QtWidgets.QCheckBox(self.groupBox_Scanning)
        self.checkBox_followPeak.setGeometry(QtCore.QRect(80, 124, 63, 700))
        self.checkBox_followPeak.setObjectName("checkBox_followPeak")
        self.label_3 = QtWidgets.QLabel(self.groupBox_Scanning)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 31, 28))
        self.label_3.setObjectName("label_3")
        self.lineEdit_numberOfScans = QtWidgets.QLineEdit(self.groupBox_Scanning)
        self.lineEdit_numberOfScans.setGeometry(QtCore.QRect(45, 122, 31, 20))
        self.lineEdit_numberOfScans.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_numberOfScans.setObjectName("lineEdit_numberOfScans")
        self.File_work.addItem(self.page_2, "")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 300, 541))
        self.page_6.setMinimumSize(QtCore.QSize(0, 0))
        self.page_6.setObjectName("page_6")
        self.groupBox_5 = QtWidgets.QGroupBox(self.page_6)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 180, 291, 161))
        self.groupBox_5.setObjectName("groupBox_5")
        self.lineEdit_laser_lambda_scanning_min = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_laser_lambda_scanning_min.setGeometry(QtCore.QRect(30, 50, 61, 20))
        self.lineEdit_laser_lambda_scanning_min.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_laser_lambda_scanning_min.setObjectName("lineEdit_laser_lambda_scanning_min")
        self.lineEdit_laser_lambda_scanning_max = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_laser_lambda_scanning_max.setGeometry(QtCore.QRect(110, 50, 61, 20))
        self.lineEdit_laser_lambda_scanning_max.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_laser_lambda_scanning_max.setObjectName("lineEdit_laser_lambda_scanning_max")
        self.label_16 = QtWidgets.QLabel(self.groupBox_5)
        self.label_16.setGeometry(QtCore.QRect(50, 22, 47, 21))
        self.label_16.setObjectName("label_16")
        self.label_18 = QtWidgets.QLabel(self.groupBox_5)
        self.label_18.setGeometry(QtCore.QRect(130, 22, 47, 21))
        self.label_18.setObjectName("label_18")
        self.lineEdit_laser_lambda_scanning_step = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_laser_lambda_scanning_step.setGeometry(QtCore.QRect(210, 50, 41, 20))
        self.lineEdit_laser_lambda_scanning_step.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_laser_lambda_scanning_step.setObjectName("lineEdit_laser_lambda_scanning_step")
        self.label_19 = QtWidgets.QLabel(self.groupBox_5)
        self.label_19.setGeometry(QtCore.QRect(210, 22, 47, 21))
        self.label_19.setObjectName("label_19")
        self.pushButton_scan_laser_wavelength = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_scan_laser_wavelength.setGeometry(QtCore.QRect(200, 90, 75, 23))
        self.pushButton_scan_laser_wavelength.setCheckable(True)
        self.pushButton_scan_laser_wavelength.setObjectName("pushButton_scan_laser_wavelength")
        self.label_20 = QtWidgets.QLabel(self.groupBox_5)
        self.label_20.setGeometry(QtCore.QRect(10, 90, 121, 21))
        self.label_20.setObjectName("label_20")
        self.label_current_scanning_laser_wavelength = QtWidgets.QLabel(self.groupBox_5)
        self.label_current_scanning_laser_wavelength.setGeometry(QtCore.QRect(10, 120, 101, 21))
        self.label_current_scanning_laser_wavelength.setObjectName("label_current_scanning_laser_wavelength")
        self.groupBox_7 = QtWidgets.QGroupBox(self.page_6)
        self.groupBox_7.setGeometry(QtCore.QRect(0, 20, 301, 141))
        self.groupBox_7.setObjectName("groupBox_7")
        self.lineEdit_laser_lambda = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_laser_lambda.setGeometry(QtCore.QRect(10, 40, 61, 20))
        self.lineEdit_laser_lambda.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_laser_lambda.setObjectName("lineEdit_laser_lambda")
        self.lineEdit_laser_power = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_laser_power.setGeometry(QtCore.QRect(89, 41, 51, 20))
        self.lineEdit_laser_power.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_laser_power.setObjectName("lineEdit_laser_power")
        self.label_21 = QtWidgets.QLabel(self.groupBox_7)
        self.label_21.setGeometry(QtCore.QRect(80, 20, 71, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_7)
        self.label_22.setGeometry(QtCore.QRect(10, 20, 47, 13))
        self.label_22.setObjectName("label_22")
        self.pushButton_laser_On = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_laser_On.setGeometry(QtCore.QRect(220, 40, 75, 23))
        self.pushButton_laser_On.setCheckable(True)
        self.pushButton_laser_On.setChecked(False)
        self.pushButton_laser_On.setObjectName("pushButton_laser_On")
        self.lineEdit_laser_fine_tune = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_laser_fine_tune.setEnabled(False)
        self.lineEdit_laser_fine_tune.setGeometry(QtCore.QRect(10, 90, 61, 20))
        self.lineEdit_laser_fine_tune.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_laser_fine_tune.setObjectName("lineEdit_laser_fine_tune")
        self.label_23 = QtWidgets.QLabel(self.groupBox_7)
        self.label_23.setGeometry(QtCore.QRect(10, 70, 91, 20))
        self.label_23.setObjectName("label_23")
        self.comboBox_laser_mode = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_laser_mode.setEnabled(False)
        self.comboBox_laser_mode.setGeometry(QtCore.QRect(150, 40, 61, 22))
        self.comboBox_laser_mode.setEditable(False)
        self.comboBox_laser_mode.setObjectName("comboBox_laser_mode")
        self.comboBox_laser_mode.addItem("")
        self.comboBox_laser_mode.addItem("")
        self.comboBox_laser_mode.addItem("")
        self.label_25 = QtWidgets.QLabel(self.groupBox_7)
        self.label_25.setGeometry(QtCore.QRect(150, 20, 61, 16))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.groupBox_10 = QtWidgets.QGroupBox(self.page_6)
        self.groupBox_10.setGeometry(QtCore.QRect(0, 350, 291, 121))
        self.groupBox_10.setObjectName("groupBox_10")
        self.lineEdit_laser_lambda_sweeping_central = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_laser_lambda_sweeping_central.setGeometry(QtCore.QRect(30, 50, 61, 20))
        self.lineEdit_laser_lambda_sweeping_central.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_laser_lambda_sweeping_central.setObjectName("lineEdit_laser_lambda_sweeping_central")
        self.lineEdit_laser_sweeping_max_detuning = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_laser_sweeping_max_detuning.setGeometry(QtCore.QRect(110, 50, 61, 20))
        self.lineEdit_laser_sweeping_max_detuning.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_laser_sweeping_max_detuning.setObjectName("lineEdit_laser_sweeping_max_detuning")
        self.label_26 = QtWidgets.QLabel(self.groupBox_10)
        self.label_26.setGeometry(QtCore.QRect(36, 22, 61, 21))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_10)
        self.label_27.setGeometry(QtCore.QRect(130, 22, 47, 21))
        self.label_27.setObjectName("label_27")
        self.lineEdit_laser_lambda_sweeping_step = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_laser_lambda_sweeping_step.setGeometry(QtCore.QRect(180, 50, 41, 20))
        self.lineEdit_laser_lambda_sweeping_step.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_laser_lambda_sweeping_step.setObjectName("lineEdit_laser_lambda_sweeping_step")
        self.label_28 = QtWidgets.QLabel(self.groupBox_10)
        self.label_28.setGeometry(QtCore.QRect(185, 23, 47, 21))
        self.label_28.setObjectName("label_28")
        self.pushButton_sweep_laser_wavelength = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_sweep_laser_wavelength.setGeometry(QtCore.QRect(200, 90, 75, 23))
        self.pushButton_sweep_laser_wavelength.setCheckable(True)
        self.pushButton_sweep_laser_wavelength.setObjectName("pushButton_sweep_laser_wavelength")
        self.lineEdit_laser_lambda_sweeping_delay = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_laser_lambda_sweeping_delay.setGeometry(QtCore.QRect(230, 50, 41, 20))
        self.lineEdit_laser_lambda_sweeping_delay.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_laser_lambda_sweeping_delay.setObjectName("lineEdit_laser_lambda_sweeping_delay")
        self.label_30 = QtWidgets.QLabel(self.groupBox_10)
        self.label_30.setGeometry(QtCore.QRect(230, 23, 47, 21))
        self.label_30.setObjectName("label_30")
        self.File_work.addItem(self.page_6, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 283, 600))
        self.page_3.setMinimumSize(QtCore.QSize(0, 600))
        self.page_3.setObjectName("page_3")
        self.groupBox_save_data_2 = QtWidgets.QGroupBox(self.page_3)
        self.groupBox_save_data_2.setGeometry(QtCore.QRect(0, 88, 291, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_save_data_2.sizePolicy().hasHeightForWidth())
        self.groupBox_save_data_2.setSizePolicy(sizePolicy)
        self.groupBox_save_data_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.groupBox_save_data_2.setObjectName("groupBox_save_data_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_save_data_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_process_arb_TD_data = QtWidgets.QPushButton(self.groupBox_save_data_2)
        self.pushButton_process_arb_TD_data.setObjectName("pushButton_process_arb_TD_data")
        self.gridLayout_3.addWidget(self.pushButton_process_arb_TD_data, 5, 0, 1, 5)
        self.pushButton_choose_folder_to_process = QtWidgets.QPushButton(self.groupBox_save_data_2)
        self.pushButton_choose_folder_to_process.setObjectName("pushButton_choose_folder_to_process")
        self.gridLayout_3.addWidget(self.pushButton_choose_folder_to_process, 0, 0, 1, 1)
        self.pushButton_process_arb_spectral_data = QtWidgets.QPushButton(self.groupBox_save_data_2)
        self.pushButton_process_arb_spectral_data.setObjectName("pushButton_process_arb_spectral_data")
        self.gridLayout_3.addWidget(self.pushButton_process_arb_spectral_data, 1, 0, 1, 5)
        self.checkBox_IsShiftingWhileProcessingArbData = QtWidgets.QCheckBox(self.groupBox_save_data_2)
        self.checkBox_IsShiftingWhileProcessingArbData.setObjectName("checkBox_IsShiftingWhileProcessingArbData")
        self.gridLayout_3.addWidget(self.checkBox_IsShiftingWhileProcessingArbData, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_save_data_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 4, 0, 1, 1)
        self.checkBox_IsAveragingWhileProcessingArbData = QtWidgets.QCheckBox(self.groupBox_save_data_2)
        self.checkBox_IsAveragingWhileProcessingArbData.setObjectName("checkBox_IsAveragingWhileProcessingArbData")
        self.gridLayout_3.addWidget(self.checkBox_IsAveragingWhileProcessingArbData, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_save_data_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 6, 0, 1, 1)
        self.comboBox_TD_channel_to_plot_arb_data = QtWidgets.QComboBox(self.groupBox_save_data_2)
        self.comboBox_TD_channel_to_plot_arb_data.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_TD_channel_to_plot_arb_data.setObjectName("comboBox_TD_channel_to_plot_arb_data")
        self.comboBox_TD_channel_to_plot_arb_data.addItem("")
        self.comboBox_TD_channel_to_plot_arb_data.addItem("")
        self.comboBox_TD_channel_to_plot_arb_data.addItem("")
        self.comboBox_TD_channel_to_plot_arb_data.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_TD_channel_to_plot_arb_data, 6, 1, 1, 1)
        self.comboBox_axis_to_plot_along_arb_data = QtWidgets.QComboBox(self.groupBox_save_data_2)
        self.comboBox_axis_to_plot_along_arb_data.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_axis_to_plot_along_arb_data.setObjectName("comboBox_axis_to_plot_along_arb_data")
        self.comboBox_axis_to_plot_along_arb_data.addItem("")
        self.comboBox_axis_to_plot_along_arb_data.addItem("")
        self.comboBox_axis_to_plot_along_arb_data.addItem("")
        self.comboBox_axis_to_plot_along_arb_data.addItem("")
        self.comboBox_axis_to_plot_along_arb_data.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_axis_to_plot_along_arb_data, 4, 1, 1, 1)
        self.pushButton_plotSampleShape_arb_data = QtWidgets.QPushButton(self.groupBox_save_data_2)
        self.pushButton_plotSampleShape_arb_data.setObjectName("pushButton_plotSampleShape_arb_data")
        self.gridLayout_3.addWidget(self.pushButton_plotSampleShape_arb_data, 4, 3, 1, 1)
        self.label_folder_to_process_files = QtWidgets.QLabel(self.groupBox_save_data_2)
        self.label_folder_to_process_files.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_folder_to_process_files.setObjectName("label_folder_to_process_files")
        self.gridLayout_3.addWidget(self.label_folder_to_process_files, 0, 1, 1, 1)
        self.comboBox_type_of_data = QtWidgets.QComboBox(self.groupBox_save_data_2)
        self.comboBox_type_of_data.setObjectName("comboBox_type_of_data")
        self.comboBox_type_of_data.addItem("")
        self.comboBox_type_of_data.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_type_of_data, 0, 3, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.page_3)
        self.groupBox.setGeometry(QtCore.QRect(0, 300, 301, 271))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 180, 281, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_analyzer_extractERV = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_analyzer_extractERV.setGeometry(QtCore.QRect(150, 40, 121, 31))
        self.pushButton_analyzer_extractERV.setObjectName("pushButton_analyzer_extractERV")
        self.lineEdit_analyzer_wavelength_min = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_analyzer_wavelength_min.setGeometry(QtCore.QRect(90, 20, 60, 20))
        self.lineEdit_analyzer_wavelength_min.setObjectName("lineEdit_analyzer_wavelength_min")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(10, 14, 81, 31))
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.lineEdit_analyzer_wavelength_max = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_analyzer_wavelength_max.setGeometry(QtCore.QRect(160, 20, 60, 20))
        self.lineEdit_analyzer_wavelength_max.setObjectName("lineEdit_analyzer_wavelength_max")
        self.pushButton_analyzer_choose_file_spectrogram = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_analyzer_choose_file_spectrogram.setGeometry(QtCore.QRect(20, 30, 100, 23))
        self.pushButton_analyzer_choose_file_spectrogram.setObjectName("pushButton_analyzer_choose_file_spectrogram")
        self.label_analyzer_folder = QtWidgets.QLabel(self.groupBox)
        self.label_analyzer_folder.setGeometry(QtCore.QRect(159, 30, 121, 23))
        self.label_analyzer_folder.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_analyzer_folder.setObjectName("label_analyzer_folder")
        self.pushButton_analyzer_plot2D = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_analyzer_plot2D.setGeometry(QtCore.QRect(10, 60, 51, 23))
        self.pushButton_analyzer_plot2D.setObjectName("pushButton_analyzer_plot2D")
        self.pushButton_analyzer_plotSampleShape = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_analyzer_plotSampleShape.setGeometry(QtCore.QRect(73, 60, 101, 23))
        self.pushButton_analyzer_plotSampleShape.setObjectName("pushButton_analyzer_plotSampleShape")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 90, 281, 80))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton_analyzer_plotSlice = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_analyzer_plotSlice.setGeometry(QtCore.QRect(10, 20, 75, 23))
        self.pushButton_analyzer_plotSlice.setObjectName("pushButton_analyzer_plotSlice")
        self.lineEdit_slice_position = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_slice_position.setGeometry(QtCore.QRect(100, 20, 41, 21))
        self.lineEdit_slice_position.setObjectName("lineEdit_slice_position")
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(150, 20, 91, 16))
        self.label_14.setObjectName("label_14")
        self.comboBox_axis_to_analyze_along_arb_data = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_axis_to_analyze_along_arb_data.setGeometry(QtCore.QRect(240, 20, 33, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_axis_to_analyze_along_arb_data.sizePolicy().hasHeightForWidth())
        self.comboBox_axis_to_analyze_along_arb_data.setSizePolicy(sizePolicy)
        self.comboBox_axis_to_analyze_along_arb_data.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_axis_to_analyze_along_arb_data.setObjectName("comboBox_axis_to_analyze_along_arb_data")
        self.comboBox_axis_to_analyze_along_arb_data.addItem("")
        self.comboBox_axis_to_analyze_along_arb_data.addItem("")
        self.comboBox_axis_to_analyze_along_arb_data.addItem("")
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setGeometry(QtCore.QRect(70, 40, 111, 41))
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName("label_17")
        self.lineEdit_analyzer_resonance_level = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_analyzer_resonance_level.setGeometry(QtCore.QRect(190, 50, 41, 20))
        self.lineEdit_analyzer_resonance_level.setObjectName("lineEdit_analyzer_resonance_level")
        self.pushButton_analyzer_save_cropped_data = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_analyzer_save_cropped_data.setGeometry(QtCore.QRect(183, 60, 101, 23))
        self.pushButton_analyzer_save_cropped_data.setObjectName("pushButton_analyzer_save_cropped_data")
        self.groupBox_8 = QtWidgets.QGroupBox(self.page_3)
        self.groupBox_8.setGeometry(QtCore.QRect(-10, 0, 291, 80))
        self.groupBox_8.setObjectName("groupBox_8")
        self.pushButton_analyzer_plot_single_spectrum_from_file = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_analyzer_plot_single_spectrum_from_file.setGeometry(QtCore.QRect(10, 30, 100, 23))
        self.pushButton_analyzer_plot_single_spectrum_from_file.setObjectName("pushButton_analyzer_plot_single_spectrum_from_file")
        self.label_analyzer_single_spectrum_file = QtWidgets.QLabel(self.groupBox_8)
        self.label_analyzer_single_spectrum_file.setGeometry(QtCore.QRect(150, 30, 121, 23))
        self.label_analyzer_single_spectrum_file.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_analyzer_single_spectrum_file.setObjectName("label_analyzer_single_spectrum_file")
        self.File_work.addItem(self.page_3, "")
        self.gridLayout_4.addWidget(self.File_work, 0, 1, 2, 1)
        self.groupBox_spectrum = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_spectrum.sizePolicy().hasHeightForWidth())
        self.groupBox_spectrum.setSizePolicy(sizePolicy)
        self.groupBox_spectrum.setMinimumSize(QtCore.QSize(550, 550))
        self.groupBox_spectrum.setSizeIncrement(QtCore.QSize(0, 0))
        self.groupBox_spectrum.setBaseSize(QtCore.QSize(0, 0))
        self.groupBox_spectrum.setObjectName("groupBox_spectrum")
        self.gridLayout_4.addWidget(self.groupBox_spectrum, 0, 2, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1115, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.File_work.setCurrentIndex(0)
        self.tabWidget_instruments.setCurrentIndex(0)
        self.comboBox_axis_to_plot_along.setCurrentIndex(2)
        self.comboBox_axis_to_plot_along_arb_data.setCurrentIndex(2)
        self.comboBox_axis_to_analyze_along_arb_data.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_11.setTitle(_translate("MainWindow", "FFT filter"))
        self.EditLine_FilterLowFreqEdge.setText(_translate("MainWindow", "0.00001"))
        self.EditLine_FilterHighFreqEdge.setText(_translate("MainWindow", "0.01"))
        self.CheckBox_ApplyFFTFilter.setText(_translate("MainWindow", "Apply"))
        self.EditLine_FilterPointsToCut.setText(_translate("MainWindow", "100"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Range, nm"))
        self.EditLine_StartWavelength.setText(_translate("MainWindow", "1550"))
        self.EditLine_StopWavelength.setText(_translate("MainWindow", "1551"))
        self.pushButton_getRange.setText(_translate("MainWindow", "Get range"))
        self.CheckBox_FreezeSpectrum.setText(_translate("MainWindow", "Freeze"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Connection"))
        self.pushButton_StagesConnect.setText(_translate("MainWindow", "Stages"))
        self.pushButton_OSA_connect.setText(_translate("MainWindow", "OSA"))
        self.pushButton_scope_connect.setText(_translate("MainWindow", "Oscilloscope"))
        self.pushButton_laser_connect.setText(_translate("MainWindow", "Laser Pure Ph"))
        self.comboBox_Type_of_OSA.setItemText(0, _translate("MainWindow", "APEX"))
        self.comboBox_Type_of_OSA.setItemText(1, _translate("MainWindow", "Luna"))
        self.comboBox_Type_of_OSA.setItemText(2, _translate("MainWindow", "Yokogawa"))
        self.comboBox_Type_of_OSA.setItemText(3, _translate("MainWindow", "Astro interrogator"))
        self.comboBox_Type_of_Stages.setItemText(0, _translate("MainWindow", "3x Standa"))
        self.comboBox_Type_of_Stages.setItemText(1, _translate("MainWindow", "2x Thorlabs"))
        self.lineEdit_laser_COMport.setText(_translate("MainWindow", "8"))
        self.label_24.setText(_translate("MainWindow", "Com port"))
        self.pushButton_zeroing_stages.setText(_translate("MainWindow", "Zeroing"))
        self.groupBox_features.setTitle(_translate("MainWindow", "OSA features:"))
        self.comboBox_APEX_mode.setItemText(0, _translate("MainWindow", "OSA"))
        self.comboBox_APEX_mode.setItemText(1, _translate("MainWindow", "Tracking generator"))
        self.comboBox_Luna_mode.setItemText(0, _translate("MainWindow", "Common .pkl files"))
        self.comboBox_Luna_mode.setItemText(1, _translate("MainWindow", "Luna binary files"))
        self.label_Luna_mode.setText(_translate("MainWindow", "Luna output mode"))
        self.label_29.setText(_translate("MainWindow", "APEX mode"))
        self.File_work.setItemText(self.File_work.indexOf(self.page), _translate("MainWindow", "Connection"))
        self.label.setText(_translate("MainWindow", "Set channel"))
        self.comboBox_interrogatorChannel.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_interrogatorChannel.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_interrogatorChannel.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_interrogatorChannel.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_interrogatorChannel.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox_interrogatorChannel.setItemText(5, _translate("MainWindow", "5"))
        self.comboBox_interrogatorChannel.setItemText(6, _translate("MainWindow", "6"))
        self.comboBox_interrogatorChannel.setItemText(7, _translate("MainWindow", "7"))
        self.pushButton_OSA_Acquire.setText(_translate("MainWindow", "Single"))
        self.pushButton_OSA_AcquireRep.setText(_translate("MainWindow", "Repeat"))
        self.checkBox_HighRes.setText(_translate("MainWindow", "High res"))
        self.pushButton_OSA_AcquireAll.setText(_translate("MainWindow", "Single All"))
        self.tabWidget_instruments.setTabText(self.tabWidget_instruments.indexOf(self.groupBox_OSA_control), _translate("MainWindow", "OSA"))
        self.pushButton_scope_repeat.setText(_translate("MainWindow", "Repeat"))
        self.pushButton_scope_single.setText(_translate("MainWindow", "Single"))
        self.label_10.setText(_translate("MainWindow", "Channels"))
        self.checkBox_ScopeCh1.setText(_translate("MainWindow", "1"))
        self.checkBox_ScopeCh2.setText(_translate("MainWindow", "2"))
        self.checkBox_ScopeCh3.setText(_translate("MainWindow", "3"))
        self.checkBox_ScopeCh4.setText(_translate("MainWindow", "4"))
        self.tabWidget_instruments.setTabText(self.tabWidget_instruments.indexOf(self.groupBox_scope_control), _translate("MainWindow", "Scope"))
        self.groupBox_stand.setTitle(_translate("MainWindow", "Stages"))
        self.pushButton_MoveMinusX.setText(_translate("MainWindow", "-X"))
        self.pushButton_MovePlusY.setText(_translate("MainWindow", "+Y"))
        self.pushButton_MoveMinusZ.setText(_translate("MainWindow", "-Z"))
        self.lineEdit_StepZ.setText(_translate("MainWindow", "20"))
        self.pushButton_MovePlusZ.setText(_translate("MainWindow", "+Z"))
        self.pushButton_MovePlusX.setText(_translate("MainWindow", "+X"))
        self.lineEdit_StepY.setText(_translate("MainWindow", "20"))
        self.pushButton_MoveMinusY.setText(_translate("MainWindow", "-Y"))
        self.lineEdit_StepX.setText(_translate("MainWindow", "20"))
        self.label_PositionZ.setText(_translate("MainWindow", "0"))
        self.label_AbsPositionX.setText(_translate("MainWindow", "0"))
        self.pushButton_zeroingPositions.setText(_translate("MainWindow", "Zeroing positions"))
        self.label_PositionY.setText(_translate("MainWindow", "0"))
        self.label_PositionX.setText(_translate("MainWindow", "0"))
        self.label_AbsPositionY.setText(_translate("MainWindow", "0"))
        self.label_AbsPositionZ.setText(_translate("MainWindow", "0"))
        self.label_11.setText(_translate("MainWindow", "Rel.pos."))
        self.label_12.setText(_translate("MainWindow", "Abs.pos."))
        self.groupBox_save_data.setTitle(_translate("MainWindow", "Work with files"))
        self.pushButton_LoadParameters.setText(_translate("MainWindow", "Load param"))
        self.EditLine_saveSpectrumName.setText(_translate("MainWindow", "File Name"))
        self.pushButton_save_data.setText(_translate("MainWindow", "Save data"))
        self.pushButton_SaveParameters.setText(_translate("MainWindow", "Save param"))
        self.pushButton_processTDData.setText(_translate("MainWindow", "Process TD"))
        self.checkBox_IsShiftingWhileProcessing.setText(_translate("MainWindow", "Shift spectra"))
        self.checkBox_IsAveragingWhileProcessing.setText(_translate("MainWindow", "Average "))
        self.pushButton_processSpectralData.setToolTip(_translate("MainWindow", "Process spectra"))
        self.pushButton_processSpectralData.setText(_translate("MainWindow", "Process spectra"))
        self.comboBox_TD_channel_to_plot.setToolTip(_translate("MainWindow", "Choose channel to plot"))
        self.comboBox_TD_channel_to_plot.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_TD_channel_to_plot.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_TD_channel_to_plot.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_TD_channel_to_plot.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_axis_to_plot_along.setToolTip(_translate("MainWindow", "Choose channel to plot"))
        self.comboBox_axis_to_plot_along.setCurrentText(_translate("MainWindow", "Z"))
        self.comboBox_axis_to_plot_along.setItemText(0, _translate("MainWindow", "X"))
        self.comboBox_axis_to_plot_along.setItemText(1, _translate("MainWindow", "Y"))
        self.comboBox_axis_to_plot_along.setItemText(2, _translate("MainWindow", "Z"))
        self.comboBox_axis_to_plot_along.setItemText(3, _translate("MainWindow", "W"))
        self.comboBox_axis_to_plot_along.setItemText(4, _translate("MainWindow", "p"))
        self.pushButton_plotSampleShape.setText(_translate("MainWindow", "Plot sample shape"))
        self.groupBox_Scanning.setTitle(_translate("MainWindow", "Scanning"))
        self.label_4.setText(_translate("MainWindow", "Scanning step"))
        self.pushButton_Scanning.setText(_translate("MainWindow", "Scanning"))
        self.label_5.setText(_translate("MainWindow", "Searching step"))
        self.lineEdit_CurrentFile.setText(_translate("MainWindow", "1"))
        self.label_8.setText(_translate("MainWindow", "from _ "))
        self.lineEdit_SearchingStep.setText(_translate("MainWindow", "30"))
        self.label_7.setText(_translate("MainWindow", "Level to recognize contact"))
        self.lineEdit_ScanningStep.setText(_translate("MainWindow", "30"))
        self.comboBox_ScanningType.setItemText(0, _translate("MainWindow", "Along Z, get contact along X"))
        self.comboBox_ScanningType.setItemText(1, _translate("MainWindow", "Along Y, get contact along X"))
        self.comboBox_ScanningType.setItemText(2, _translate("MainWindow", "Along Y, get contact along Z"))
        self.comboBox_ScanningType.setItemText(3, _translate("MainWindow", "Along X, get contact along Z"))
        self.lineEdit_LevelToDetectContact.setText(_translate("MainWindow", "-35"))
        self.lineEdit_StopFile.setText(_translate("MainWindow", "100"))
        self.label_2.setText(_translate("MainWindow", "to"))
        self.label_6.setText(_translate("MainWindow", "Losing contact step"))
        self.lineEdit_BackStep.setText(_translate("MainWindow", "50"))
        self.checkBox_saveDifference.setText(_translate("MainWindow", "Save difference"))
        self.checkBox_searchContact.setToolTip(_translate("MainWindow", "Search contact at each scanning point"))
        self.checkBox_searchContact.setText(_translate("MainWindow", "Search contact"))
        self.checkBox_SqueezeSpan.setToolTip(_translate("MainWindow", "Squeeze Span while search contact"))
        self.checkBox_SqueezeSpan.setText(_translate("MainWindow", "Squeeze Span"))
        self.checkBox_followPeak.setToolTip(_translate("MainWindow", "Set span center to the peak position"))
        self.checkBox_followPeak.setText(_translate("MainWindow", "Follow peak"))
        self.label_3.setText(_translate("MainWindow", "#sweeps"))
        self.lineEdit_numberOfScans.setText(_translate("MainWindow", "1"))
        self.File_work.setItemText(self.File_work.indexOf(self.page_2), _translate("MainWindow", "Experiment\'s flow"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Scanning wavelength and save data"))
        self.lineEdit_laser_lambda_scanning_min.setText(_translate("MainWindow", "1550"))
        self.lineEdit_laser_lambda_scanning_max.setText(_translate("MainWindow", "1550.5"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p>λ<span style=\" vertical-align:sub;\">min</span>, nm</p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p>λ<span style=\" vertical-align:sub;\">max</span>, nm</p></body></html>"))
        self.lineEdit_laser_lambda_scanning_step.setText(_translate("MainWindow", "20"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p>dλ, pm</p></body></html>"))
        self.pushButton_scan_laser_wavelength.setText(_translate("MainWindow", "Scanning"))
        self.label_20.setText(_translate("MainWindow", "Current wavelength"))
        self.label_current_scanning_laser_wavelength.setText(_translate("MainWindow", "1550"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Laser parameters"))
        self.lineEdit_laser_lambda.setText(_translate("MainWindow", "1550.001"))
        self.lineEdit_laser_power.setText(_translate("MainWindow", "1000"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p>P, dBm*100</p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p>λ, nm</p></body></html>"))
        self.pushButton_laser_On.setText(_translate("MainWindow", "Laser On"))
        self.lineEdit_laser_fine_tune.setText(_translate("MainWindow", "0"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p>Fine tune, pm</p></body></html>"))
        self.comboBox_laser_mode.setItemText(0, _translate("MainWindow", "Dither"))
        self.comboBox_laser_mode.setItemText(1, _translate("MainWindow", "Nodither"))
        self.comboBox_laser_mode.setItemText(2, _translate("MainWindow", "Whisper"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p>Mode</p></body></html>"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Sweeping wavelength fast"))
        self.lineEdit_laser_lambda_sweeping_central.setText(_translate("MainWindow", "1550"))
        self.lineEdit_laser_sweeping_max_detuning.setText(_translate("MainWindow", "100"))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p>λ<span style=\" vertical-align:sub;\">central</span>, nm</p></body></html>"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p>Dλ, pm</p></body></html>"))
        self.lineEdit_laser_lambda_sweeping_step.setText(_translate("MainWindow", "1"))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p>dλ, pm</p></body></html>"))
        self.pushButton_sweep_laser_wavelength.setText(_translate("MainWindow", "Sweeping"))
        self.lineEdit_laser_lambda_sweeping_delay.setText(_translate("MainWindow", "0"))
        self.label_30.setText(_translate("MainWindow", "<html><head/><body><p>delay, s</p></body></html>"))
        self.File_work.setItemText(self.File_work.indexOf(self.page_6), _translate("MainWindow", "Laser control"))
        self.groupBox_save_data_2.setTitle(_translate("MainWindow", "Work with raw files"))
        self.pushButton_process_arb_TD_data.setText(_translate("MainWindow", "Process time dinamics from raw data"))
        self.pushButton_choose_folder_to_process.setText(_translate("MainWindow", "Folder"))
        self.pushButton_process_arb_spectral_data.setText(_translate("MainWindow", "Process spectra from raw data"))
        self.checkBox_IsShiftingWhileProcessingArbData.setToolTip(_translate("MainWindow", "Calculate the averaged position of the spectrum (mainly for Apex)"))
        self.checkBox_IsShiftingWhileProcessingArbData.setText(_translate("MainWindow", "Shifting"))
        self.label_9.setText(_translate("MainWindow", "Plot along"))
        self.checkBox_IsAveragingWhileProcessingArbData.setToolTip(_translate("MainWindow", "Straightforward averaging of all spectra at the point"))
        self.checkBox_IsAveragingWhileProcessingArbData.setText(_translate("MainWindow", "Averaging"))
        self.label_13.setText(_translate("MainWindow", "Channel number"))
        self.comboBox_TD_channel_to_plot_arb_data.setToolTip(_translate("MainWindow", "Choose channel to plot"))
        self.comboBox_TD_channel_to_plot_arb_data.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_TD_channel_to_plot_arb_data.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_TD_channel_to_plot_arb_data.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_TD_channel_to_plot_arb_data.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_axis_to_plot_along_arb_data.setToolTip(_translate("MainWindow", "Choose channel to plot"))
        self.comboBox_axis_to_plot_along_arb_data.setCurrentText(_translate("MainWindow", "Z"))
        self.comboBox_axis_to_plot_along_arb_data.setItemText(0, _translate("MainWindow", "X"))
        self.comboBox_axis_to_plot_along_arb_data.setItemText(1, _translate("MainWindow", "Y"))
        self.comboBox_axis_to_plot_along_arb_data.setItemText(2, _translate("MainWindow", "Z"))
        self.comboBox_axis_to_plot_along_arb_data.setItemText(3, _translate("MainWindow", "W"))
        self.comboBox_axis_to_plot_along_arb_data.setItemText(4, _translate("MainWindow", "p"))
        self.pushButton_plotSampleShape_arb_data.setText(_translate("MainWindow", "Plot sample shape"))
        self.label_folder_to_process_files.setText(_translate("MainWindow", "none"))
        self.comboBox_type_of_data.setItemText(0, _translate("MainWindow", "bin"))
        self.comboBox_type_of_data.setItemText(1, _translate("MainWindow", "txt"))
        self.groupBox.setTitle(_translate("MainWindow", "Analyze spectrogram"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Get ERV"))
        self.pushButton_analyzer_extractERV.setText(_translate("MainWindow", "Get ERV and linewidths"))
        self.lineEdit_analyzer_wavelength_min.setText(_translate("MainWindow", "1550"))
        self.label_15.setText(_translate("MainWindow", "Wavelengths: min, max"))
        self.lineEdit_analyzer_wavelength_max.setText(_translate("MainWindow", "1551"))
        self.pushButton_analyzer_choose_file_spectrogram.setText(_translate("MainWindow", "File to analyze"))
        self.label_analyzer_folder.setText(_translate("MainWindow", "none"))
        self.pushButton_analyzer_plot2D.setText(_translate("MainWindow", "Plot 2D"))
        self.pushButton_analyzer_plotSampleShape.setText(_translate("MainWindow", "Plot sample shape"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Plot slice"))
        self.pushButton_analyzer_plotSlice.setText(_translate("MainWindow", "Plot slice at"))
        self.lineEdit_slice_position.setText(_translate("MainWindow", "500"))
        self.label_14.setText(_translate("MainWindow", "steps along axis"))
        self.comboBox_axis_to_analyze_along_arb_data.setToolTip(_translate("MainWindow", "Choose channel to plot"))
        self.comboBox_axis_to_analyze_along_arb_data.setItemText(0, _translate("MainWindow", "X"))
        self.comboBox_axis_to_analyze_along_arb_data.setItemText(1, _translate("MainWindow", "Y"))
        self.comboBox_axis_to_analyze_along_arb_data.setItemText(2, _translate("MainWindow", "Z"))
        self.label_17.setText(_translate("MainWindow", "Level to peak analyzer"))
        self.lineEdit_analyzer_resonance_level.setText(_translate("MainWindow", "20"))
        self.pushButton_analyzer_save_cropped_data.setText(_translate("MainWindow", "Save cropped data"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Single spectrum from file"))
        self.pushButton_analyzer_plot_single_spectrum_from_file.setText(_translate("MainWindow", "Choose  spectrum"))
        self.label_analyzer_single_spectrum_file.setText(_translate("MainWindow", "none"))
        self.File_work.setItemText(self.File_work.indexOf(self.page_3), _translate("MainWindow", "Work with files"))
        self.groupBox_spectrum.setTitle(_translate("MainWindow", "Graph"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

