# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1183, 640)
        MainWindow.setMinimumSize(QtCore.QSize(730, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 10000))
        MainWindow.setAcceptDrops(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(255)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setBaseSize(QtCore.QSize(-25536, 0))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setEnabled(True)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1163, 579))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_9 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setMinimumSize(QtCore.QSize(260, 50))
        self.groupBox_9.setMaximumSize(QtCore.QSize(10000000, 50))
        self.groupBox_9.setObjectName("groupBox_9")
        self.lineEdit_StartWavelength = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_StartWavelength.setGeometry(QtCore.QRect(10, 20, 61, 20))
        self.lineEdit_StartWavelength.setMaxLength(8)
        self.lineEdit_StartWavelength.setObjectName("lineEdit_StartWavelength")
        self.lineEdit_StopWavelength = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_StopWavelength.setGeometry(QtCore.QRect(80, 20, 71, 20))
        self.lineEdit_StopWavelength.setMaxLength(8)
        self.lineEdit_StopWavelength.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.lineEdit_StopWavelength.setObjectName("lineEdit_StopWavelength")
        self.pushButton_getRange = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_getRange.setGeometry(QtCore.QRect(160, 20, 71, 21))
        self.pushButton_getRange.setObjectName("pushButton_getRange")
        self.checkBox_FreezeSpectrum = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_FreezeSpectrum.setGeometry(QtCore.QRect(340, 20, 60, 20))
        self.checkBox_FreezeSpectrum.setObjectName("checkBox_FreezeSpectrum")
        self.pushButton_set_max_OSA_range = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_set_max_OSA_range.setGeometry(QtCore.QRect(240, 20, 91, 21))
        self.pushButton_set_max_OSA_range.setObjectName("pushButton_set_max_OSA_range")
        self.gridLayout_4.addWidget(self.groupBox_9, 1, 2, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_11.sizePolicy().hasHeightForWidth())
        self.groupBox_11.setSizePolicy(sizePolicy)
        self.groupBox_11.setMinimumSize(QtCore.QSize(300, 50))
        self.groupBox_11.setMaximumSize(QtCore.QSize(300, 50))
        self.groupBox_11.setObjectName("groupBox_11")
        self.lineEdit_FilterLowFreqEdge = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_FilterLowFreqEdge.setGeometry(QtCore.QRect(87, 23, 70, 17))
        self.lineEdit_FilterLowFreqEdge.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_FilterLowFreqEdge.setObjectName("lineEdit_FilterLowFreqEdge")
        self.lineEdit_FilterHighFreqEdge = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_FilterHighFreqEdge.setGeometry(QtCore.QRect(163, 23, 71, 17))
        self.lineEdit_FilterHighFreqEdge.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_FilterHighFreqEdge.setObjectName("lineEdit_FilterHighFreqEdge")
        self.checkBox_ApplyFFTFilter = QtWidgets.QCheckBox(self.groupBox_11)
        self.checkBox_ApplyFFTFilter.setGeometry(QtCore.QRect(240, 23, 50, 17))
        self.checkBox_ApplyFFTFilter.setObjectName("checkBox_ApplyFFTFilter")
        self.lineEdit_FilterPointsToCut = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_FilterPointsToCut.setGeometry(QtCore.QRect(10, 23, 71, 17))
        self.lineEdit_FilterPointsToCut.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_FilterPointsToCut.setObjectName("lineEdit_FilterPointsToCut")
        self.gridLayout_4.addWidget(self.groupBox_11, 1, 3, 1, 1)
        self.groupBox_spectrum = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_spectrum.sizePolicy().hasHeightForWidth())
        self.groupBox_spectrum.setSizePolicy(sizePolicy)
        self.groupBox_spectrum.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_spectrum.setSizeIncrement(QtCore.QSize(0, 0))
        self.groupBox_spectrum.setBaseSize(QtCore.QSize(0, 0))
        self.groupBox_spectrum.setToolTipDuration(10)
        self.groupBox_spectrum.setObjectName("groupBox_spectrum")
        self.label_analyzer_plotting_file = QtWidgets.QLabel(self.groupBox_spectrum)
        self.label_analyzer_plotting_file.setGeometry(QtCore.QRect(-170, 240, 161, 23))
        self.label_analyzer_plotting_file.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_analyzer_plotting_file.setObjectName("label_analyzer_plotting_file")
        self.gridLayout_4.addWidget(self.groupBox_spectrum, 0, 2, 1, 2)
        self.Toolbox = QtWidgets.QToolBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Toolbox.sizePolicy().hasHeightForWidth())
        self.Toolbox.setSizePolicy(sizePolicy)
        self.Toolbox.setMinimumSize(QtCore.QSize(300, 0))
        self.Toolbox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.Toolbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Toolbox.setObjectName("Toolbox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 300, 426))
        self.page.setObjectName("page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_StagesConnect = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_StagesConnect.setGeometry(QtCore.QRect(110, 23, 91, 23))
        self.pushButton_StagesConnect.setCheckable(False)
        self.pushButton_StagesConnect.setObjectName("pushButton_StagesConnect")
        self.pushButton_scope_connect = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_scope_connect.setGeometry(QtCore.QRect(110, 52, 91, 23))
        self.pushButton_scope_connect.setCheckable(False)
        self.pushButton_scope_connect.setObjectName("pushButton_scope_connect")
        self.pushButton_laser_connect = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_laser_connect.setGeometry(QtCore.QRect(110, 81, 91, 23))
        self.pushButton_laser_connect.setObjectName("pushButton_laser_connect")
        self.comboBox_Type_of_Stages = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_Type_of_Stages.setGeometry(QtCore.QRect(10, 24, 91, 20))
        self.comboBox_Type_of_Stages.setObjectName("comboBox_Type_of_Stages")
        self.comboBox_Type_of_Stages.addItem("")
        self.comboBox_Type_of_Stages.addItem("")
        self.comboBox_Type_of_Stages.addItem("")
        self.lineEdit_laser_COMport = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_laser_COMport.setGeometry(QtCore.QRect(80, 82, 21, 20))
        self.lineEdit_laser_COMport.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_laser_COMport.setObjectName("lineEdit_laser_COMport")
        self.label_24 = QtWidgets.QLabel(self.groupBox_3)
        self.label_24.setGeometry(QtCore.QRect(10, 82, 61, 20))
        self.label_24.setObjectName("label_24")
        self.pushButton_zeroing_stages = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_zeroing_stages.setGeometry(QtCore.QRect(210, 23, 61, 21))
        self.pushButton_zeroing_stages.setObjectName("pushButton_zeroing_stages")
        self.groupBox_features = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_features.setGeometry(QtCore.QRect(0, 140, 281, 81))
        self.groupBox_features.setObjectName("groupBox_features")
        self.label_29 = QtWidgets.QLabel(self.groupBox_features)
        self.label_29.setGeometry(QtCore.QRect(10, 50, 81, 21))
        self.label_29.setObjectName("label_29")
        self.comboBox_Luna_mode = QtWidgets.QComboBox(self.groupBox_features)
        self.comboBox_Luna_mode.setGeometry(QtCore.QRect(110, 50, 91, 22))
        self.comboBox_Luna_mode.setObjectName("comboBox_Luna_mode")
        self.comboBox_Luna_mode.addItem("")
        self.comboBox_Luna_mode.addItem("")
        self.label_Luna_mode = QtWidgets.QLabel(self.groupBox_features)
        self.label_Luna_mode.setGeometry(QtCore.QRect(10, 50, 61, 20))
        self.label_Luna_mode.setObjectName("label_Luna_mode")
        self.comboBox_APEX_mode = QtWidgets.QComboBox(self.groupBox_features)
        self.comboBox_APEX_mode.setEnabled(False)
        self.comboBox_APEX_mode.setGeometry(QtCore.QRect(110, 50, 91, 21))
        self.comboBox_APEX_mode.setObjectName("comboBox_APEX_mode")
        self.comboBox_APEX_mode.addItem("")
        self.comboBox_APEX_mode.addItem("")
        self.comboBox_Type_of_OSA = QtWidgets.QComboBox(self.groupBox_features)
        self.comboBox_Type_of_OSA.setGeometry(QtCore.QRect(10, 20, 91, 20))
        self.comboBox_Type_of_OSA.setObjectName("comboBox_Type_of_OSA")
        self.comboBox_Type_of_OSA.addItem("")
        self.comboBox_Type_of_OSA.addItem("")
        self.comboBox_Type_of_OSA.addItem("")
        self.comboBox_Type_of_OSA.addItem("")
        self.pushButton_OSA_connect = QtWidgets.QPushButton(self.groupBox_features)
        self.pushButton_OSA_connect.setGeometry(QtCore.QRect(110, 20, 91, 23))
        self.pushButton_OSA_connect.setCheckable(False)
        self.pushButton_OSA_connect.setObjectName("pushButton_OSA_connect")
        self.pushButton_powermeter_connect = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_powermeter_connect.setGeometry(QtCore.QRect(110, 110, 91, 23))
        self.pushButton_powermeter_connect.setCheckable(False)
        self.pushButton_powermeter_connect.setObjectName("pushButton_powermeter_connect")
        self.pushButton_powermeter_graph = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_powermeter_graph.setEnabled(False)
        self.pushButton_powermeter_graph.setGeometry(QtCore.QRect(210, 111, 61, 21))
        self.pushButton_powermeter_graph.setCheckable(True)
        self.pushButton_powermeter_graph.setObjectName("pushButton_powermeter_graph")
        self.groupBox_features.raise_()
        self.pushButton_StagesConnect.raise_()
        self.pushButton_scope_connect.raise_()
        self.pushButton_laser_connect.raise_()
        self.comboBox_Type_of_Stages.raise_()
        self.lineEdit_laser_COMport.raise_()
        self.label_24.raise_()
        self.pushButton_zeroing_stages.raise_()
        self.pushButton_powermeter_connect.raise_()
        self.pushButton_powermeter_graph.raise_()
        self.verticalLayout.addWidget(self.groupBox_3)
        self.Toolbox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 283, 700))
        self.page_2.setMinimumSize(QtCore.QSize(0, 700))
        self.page_2.setObjectName("page_2")
        self.tabWidget_instruments = QtWidgets.QTabWidget(self.page_2)
        self.tabWidget_instruments.setEnabled(False)
        self.tabWidget_instruments.setGeometry(QtCore.QRect(0, 230, 281, 121))
        self.tabWidget_instruments.setObjectName("tabWidget_instruments")
        self.groupBox_OSA_control = QtWidgets.QWidget()
        self.groupBox_OSA_control.setObjectName("groupBox_OSA_control")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_OSA_control)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_OSA_control)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBox_interrogatorChannel = QtWidgets.QComboBox(self.groupBox_OSA_control)
        self.comboBox_interrogatorChannel.setObjectName("comboBox_interrogatorChannel")
        self.comboBox_interrogatorChannel.addItem("")
        self.comboBox_interrogatorChannel.addItem("")
        self.comboBox_interrogatorChannel.addItem("")
        self.comboBox_interrogatorChannel.addItem("")
        self.comboBox_interrogatorChannel.addItem("")
        self.comboBox_interrogatorChannel.addItem("")
        self.comboBox_interrogatorChannel.addItem("")
        self.comboBox_interrogatorChannel.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_interrogatorChannel)
        self.pushButton_OSA_Acquire = QtWidgets.QPushButton(self.groupBox_OSA_control)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_OSA_Acquire.setFont(font)
        self.pushButton_OSA_Acquire.setObjectName("pushButton_OSA_Acquire")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton_OSA_Acquire)
        self.pushButton_OSA_AcquireRep = QtWidgets.QPushButton(self.groupBox_OSA_control)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_OSA_AcquireRep.setFont(font)
        self.pushButton_OSA_AcquireRep.setCheckable(True)
        self.pushButton_OSA_AcquireRep.setObjectName("pushButton_OSA_AcquireRep")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pushButton_OSA_AcquireRep)
        self.checkBox_HighRes = QtWidgets.QCheckBox(self.groupBox_OSA_control)
        self.checkBox_HighRes.setCheckable(True)
        self.checkBox_HighRes.setObjectName("checkBox_HighRes")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.checkBox_HighRes)
        self.pushButton_OSA_AcquireAll = QtWidgets.QPushButton(self.groupBox_OSA_control)
        self.pushButton_OSA_AcquireAll.setObjectName("pushButton_OSA_AcquireAll")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButton_OSA_AcquireAll)
        self.tabWidget_instruments.addTab(self.groupBox_OSA_control, "")
        self.groupBox_scope_control = QtWidgets.QWidget()
        self.groupBox_scope_control.setObjectName("groupBox_scope_control")
        self.pushButton_scope_repeat = QtWidgets.QPushButton(self.groupBox_scope_control)
        self.pushButton_scope_repeat.setGeometry(QtCore.QRect(140, 50, 93, 28))
        self.pushButton_scope_repeat.setCheckable(True)
        self.pushButton_scope_repeat.setObjectName("pushButton_scope_repeat")
        self.pushButton_scope_single = QtWidgets.QPushButton(self.groupBox_scope_control)
        self.pushButton_scope_single.setGeometry(QtCore.QRect(10, 50, 93, 28))
        self.pushButton_scope_single.setObjectName("pushButton_scope_single")
        self.label_10 = QtWidgets.QLabel(self.groupBox_scope_control)
        self.label_10.setGeometry(QtCore.QRect(20, 15, 47, 10))
        self.label_10.setObjectName("label_10")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_scope_control)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 10, 159, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_ScopeCh1 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_ScopeCh1.setObjectName("checkBox_ScopeCh1")
        self.horizontalLayout_3.addWidget(self.checkBox_ScopeCh1)
        self.checkBox_ScopeCh2 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_ScopeCh2.setObjectName("checkBox_ScopeCh2")
        self.horizontalLayout_3.addWidget(self.checkBox_ScopeCh2)
        self.checkBox_ScopeCh3 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_ScopeCh3.setObjectName("checkBox_ScopeCh3")
        self.horizontalLayout_3.addWidget(self.checkBox_ScopeCh3)
        self.checkBox_ScopeCh4 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_ScopeCh4.setObjectName("checkBox_ScopeCh4")
        self.horizontalLayout_3.addWidget(self.checkBox_ScopeCh4)
        self.tabWidget_instruments.addTab(self.groupBox_scope_control, "")
        self.groupBox_stand = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_stand.setEnabled(False)
        self.groupBox_stand.setGeometry(QtCore.QRect(0, 0, 271, 231))
        self.groupBox_stand.setObjectName("groupBox_stand")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_stand)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_MoveMinusX = QtWidgets.QPushButton(self.groupBox_stand)
        self.pushButton_MoveMinusX.setObjectName("pushButton_MoveMinusX")
        self.gridLayout.addWidget(self.pushButton_MoveMinusX, 2, 0, 1, 1)
        self.pushButton_MovePlusY = QtWidgets.QPushButton(self.groupBox_stand)
        self.pushButton_MovePlusY.setObjectName("pushButton_MovePlusY")
        self.gridLayout.addWidget(self.pushButton_MovePlusY, 1, 1, 1, 1)
        self.pushButton_MoveMinusZ = QtWidgets.QPushButton(self.groupBox_stand)
        self.pushButton_MoveMinusZ.setObjectName("pushButton_MoveMinusZ")
        self.gridLayout.addWidget(self.pushButton_MoveMinusZ, 2, 2, 1, 1)
        self.lineEdit_StepZ = QtWidgets.QLineEdit(self.groupBox_stand)
        self.lineEdit_StepZ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_StepZ.setObjectName("lineEdit_StepZ")
        self.gridLayout.addWidget(self.lineEdit_StepZ, 0, 2, 1, 1)
        self.pushButton_MovePlusZ = QtWidgets.QPushButton(self.groupBox_stand)
        self.pushButton_MovePlusZ.setObjectName("pushButton_MovePlusZ")
        self.gridLayout.addWidget(self.pushButton_MovePlusZ, 1, 2, 1, 1)
        self.pushButton_MovePlusX = QtWidgets.QPushButton(self.groupBox_stand)
        self.pushButton_MovePlusX.setObjectName("pushButton_MovePlusX")
        self.gridLayout.addWidget(self.pushButton_MovePlusX, 1, 0, 1, 1)
        self.lineEdit_StepY = QtWidgets.QLineEdit(self.groupBox_stand)
        self.lineEdit_StepY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_StepY.setObjectName("lineEdit_StepY")
        self.gridLayout.addWidget(self.lineEdit_StepY, 0, 1, 1, 1)
        self.pushButton_MoveMinusY = QtWidgets.QPushButton(self.groupBox_stand)
        self.pushButton_MoveMinusY.setObjectName("pushButton_MoveMinusY")
        self.gridLayout.addWidget(self.pushButton_MoveMinusY, 2, 1, 1, 1)
        self.lineEdit_StepX = QtWidgets.QLineEdit(self.groupBox_stand)
        self.lineEdit_StepX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_StepX.setObjectName("lineEdit_StepX")
        self.gridLayout.addWidget(self.lineEdit_StepX, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_stand)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_PositionZ = QtWidgets.QLabel(self.groupBox_6)
        self.label_PositionZ.setGeometry(QtCore.QRect(200, 30, 51, 20))
        self.label_PositionZ.setAlignment(QtCore.Qt.AlignCenter)
        self.label_PositionZ.setObjectName("label_PositionZ")
        self.label_AbsPositionX = QtWidgets.QLabel(self.groupBox_6)
        self.label_AbsPositionX.setGeometry(QtCore.QRect(5, 70, 61, 20))
        self.label_AbsPositionX.setAlignment(QtCore.Qt.AlignCenter)
        self.label_AbsPositionX.setObjectName("label_AbsPositionX")
        self.pushButton_zeroingPositions = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_zeroingPositions.setGeometry(QtCore.QRect(90, 10, 106, 20))
        self.pushButton_zeroingPositions.setObjectName("pushButton_zeroingPositions")
        self.label_PositionY = QtWidgets.QLabel(self.groupBox_6)
        self.label_PositionY.setGeometry(QtCore.QRect(110, 30, 51, 20))
        self.label_PositionY.setAlignment(QtCore.Qt.AlignCenter)
        self.label_PositionY.setObjectName("label_PositionY")
        self.label_PositionX = QtWidgets.QLabel(self.groupBox_6)
        self.label_PositionX.setGeometry(QtCore.QRect(10, 30, 51, 20))
        self.label_PositionX.setAlignment(QtCore.Qt.AlignCenter)
        self.label_PositionX.setObjectName("label_PositionX")
        self.label_AbsPositionY = QtWidgets.QLabel(self.groupBox_6)
        self.label_AbsPositionY.setGeometry(QtCore.QRect(110, 70, 50, 16))
        self.label_AbsPositionY.setAlignment(QtCore.Qt.AlignCenter)
        self.label_AbsPositionY.setObjectName("label_AbsPositionY")
        self.label_AbsPositionZ = QtWidgets.QLabel(self.groupBox_6)
        self.label_AbsPositionZ.setGeometry(QtCore.QRect(198, 70, 55, 16))
        self.label_AbsPositionZ.setAlignment(QtCore.Qt.AlignCenter)
        self.label_AbsPositionZ.setObjectName("label_AbsPositionZ")
        self.label_11 = QtWidgets.QLabel(self.groupBox_6)
        self.label_11.setGeometry(QtCore.QRect(20, 13, 50, 13))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_6)
        self.label_12.setGeometry(QtCore.QRect(20, 53, 47, 13))
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.groupBox_6, 3, 0, 1, 3)
        self.groupBox_save_data = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_save_data.setGeometry(QtCore.QRect(0, 520, 281, 141))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_save_data.sizePolicy().hasHeightForWidth())
        self.groupBox_save_data.setSizePolicy(sizePolicy)
        self.groupBox_save_data.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.groupBox_save_data.setObjectName("groupBox_save_data")
        self.lineEdit_saveSpectrumName = QtWidgets.QLineEdit(self.groupBox_save_data)
        self.lineEdit_saveSpectrumName.setGeometry(QtCore.QRect(100, 20, 171, 16))
        self.lineEdit_saveSpectrumName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_saveSpectrumName.setObjectName("lineEdit_saveSpectrumName")
        self.pushButton_save_data = QtWidgets.QPushButton(self.groupBox_save_data)
        self.pushButton_save_data.setGeometry(QtCore.QRect(10, 20, 84, 21))
        self.pushButton_save_data.setObjectName("pushButton_save_data")
        self.pushButton_processTDData = QtWidgets.QPushButton(self.groupBox_save_data)
        self.pushButton_processTDData.setGeometry(QtCore.QRect(10, 110, 91, 21))
        self.pushButton_processTDData.setObjectName("pushButton_processTDData")
        self.pushButton_process_measured_spectral_data = QtWidgets.QPushButton(self.groupBox_save_data)
        self.pushButton_process_measured_spectral_data.setGeometry(QtCore.QRect(10, 50, 121, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_process_measured_spectral_data.setFont(font)
        self.pushButton_process_measured_spectral_data.setObjectName("pushButton_process_measured_spectral_data")
        self.comboBox_TD_channel_to_plot = QtWidgets.QComboBox(self.groupBox_save_data)
        self.comboBox_TD_channel_to_plot.setGeometry(QtCore.QRect(130, 110, 32, 20))
        self.comboBox_TD_channel_to_plot.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_TD_channel_to_plot.setObjectName("comboBox_TD_channel_to_plot")
        self.comboBox_TD_channel_to_plot.addItem("")
        self.comboBox_TD_channel_to_plot.addItem("")
        self.comboBox_TD_channel_to_plot.addItem("")
        self.comboBox_TD_channel_to_plot.addItem("")
        self.pushButton_plotSampleShape = QtWidgets.QPushButton(self.groupBox_save_data)
        self.pushButton_plotSampleShape.setGeometry(QtCore.QRect(10, 80, 121, 21))
        self.pushButton_plotSampleShape.setObjectName("pushButton_plotSampleShape")
        self.pushButton_set_spectral_processor_parameters_2 = QtWidgets.QPushButton(self.groupBox_save_data)
        self.pushButton_set_spectral_processor_parameters_2.setGeometry(QtCore.QRect(140, 50, 141, 23))
        self.pushButton_set_spectral_processor_parameters_2.setObjectName("pushButton_set_spectral_processor_parameters_2")
        self.pushButton_analyze_spectrum = QtWidgets.QPushButton(self.groupBox_save_data)
        self.pushButton_analyze_spectrum.setGeometry(QtCore.QRect(140, 80, 141, 23))
        self.pushButton_analyze_spectrum.setObjectName("pushButton_analyze_spectrum")
        self.groupBox_Scanning = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_Scanning.setEnabled(False)
        self.groupBox_Scanning.setGeometry(QtCore.QRect(0, 350, 281, 161))
        self.groupBox_Scanning.setObjectName("groupBox_Scanning")
        self.pushButton_scan_in_space = QtWidgets.QPushButton(self.groupBox_Scanning)
        self.pushButton_scan_in_space.setGeometry(QtCore.QRect(10, 30, 261, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_scan_in_space.setFont(font)
        self.pushButton_scan_in_space.setCheckable(True)
        self.pushButton_scan_in_space.setObjectName("pushButton_scan_in_space")
        self.pushButton_set_scanning_parameters = QtWidgets.QPushButton(self.groupBox_Scanning)
        self.pushButton_set_scanning_parameters.setGeometry(QtCore.QRect(10, 60, 261, 23))
        self.pushButton_set_scanning_parameters.setObjectName("pushButton_set_scanning_parameters")
        self.label_scanning_index_status = QtWidgets.QLabel(self.groupBox_Scanning)
        self.label_scanning_index_status.setGeometry(QtCore.QRect(20, 100, 181, 20))
        self.label_scanning_index_status.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_scanning_index_status.setObjectName("label_scanning_index_status")
        self.label_scanning_axis = QtWidgets.QLabel(self.groupBox_Scanning)
        self.label_scanning_axis.setGeometry(QtCore.QRect(75, 130, 16, 20))
        self.label_scanning_axis.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_scanning_axis.setObjectName("label_scanning_axis")
        self.label_scanning_final_position = QtWidgets.QLabel(self.groupBox_Scanning)
        self.label_scanning_final_position.setGeometry(QtCore.QRect(157, 130, 51, 20))
        self.label_scanning_final_position.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_scanning_final_position.setObjectName("label_scanning_final_position")
        self.label_2 = QtWidgets.QLabel(self.groupBox_Scanning)
        self.label_2.setGeometry(QtCore.QRect(20, 130, 271, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.Toolbox.addItem(self.page_2, "")
        self.page_processing = QtWidgets.QWidget()
        self.page_processing.setGeometry(QtCore.QRect(0, 0, 300, 426))
        self.page_processing.setObjectName("page_processing")
        self.groupBox_processArbData = QtWidgets.QGroupBox(self.page_processing)
        self.groupBox_processArbData.setGeometry(QtCore.QRect(0, 40, 291, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_processArbData.sizePolicy().hasHeightForWidth())
        self.groupBox_processArbData.setSizePolicy(sizePolicy)
        self.groupBox_processArbData.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.groupBox_processArbData.setObjectName("groupBox_processArbData")
        self.pushButton_process_arb_spectral_data = QtWidgets.QPushButton(self.groupBox_processArbData)
        self.pushButton_process_arb_spectral_data.setGeometry(QtCore.QRect(10, 20, 161, 23))
        self.pushButton_process_arb_spectral_data.setObjectName("pushButton_process_arb_spectral_data")
        self.pushButton_plotSampleShape_arb_data = QtWidgets.QPushButton(self.groupBox_processArbData)
        self.pushButton_plotSampleShape_arb_data.setGeometry(QtCore.QRect(10, 50, 161, 23))
        self.pushButton_plotSampleShape_arb_data.setObjectName("pushButton_plotSampleShape_arb_data")
        self.pushButton_set_spectral_processor_parameters = QtWidgets.QPushButton(self.groupBox_processArbData)
        self.pushButton_set_spectral_processor_parameters.setGeometry(QtCore.QRect(180, 20, 101, 23))
        self.pushButton_set_spectral_processor_parameters.setObjectName("pushButton_set_spectral_processor_parameters")
        self.groupBox_processArbData_2 = QtWidgets.QGroupBox(self.page_processing)
        self.groupBox_processArbData_2.setGeometry(QtCore.QRect(0, 150, 291, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_processArbData_2.sizePolicy().hasHeightForWidth())
        self.groupBox_processArbData_2.setSizePolicy(sizePolicy)
        self.groupBox_processArbData_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.groupBox_processArbData_2.setObjectName("groupBox_processArbData_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_processArbData_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_process_arb_TD_data = QtWidgets.QPushButton(self.groupBox_processArbData_2)
        self.pushButton_process_arb_TD_data.setObjectName("pushButton_process_arb_TD_data")
        self.verticalLayout_3.addWidget(self.pushButton_process_arb_TD_data)
        self.label_31 = QtWidgets.QLabel(self.groupBox_processArbData_2)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_3.addWidget(self.label_31)
        self.comboBox_TD_channel_to_plot_arb_data = QtWidgets.QComboBox(self.groupBox_processArbData_2)
        self.comboBox_TD_channel_to_plot_arb_data.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_TD_channel_to_plot_arb_data.setObjectName("comboBox_TD_channel_to_plot_arb_data")
        self.comboBox_TD_channel_to_plot_arb_data.addItem("")
        self.comboBox_TD_channel_to_plot_arb_data.addItem("")
        self.comboBox_TD_channel_to_plot_arb_data.addItem("")
        self.comboBox_TD_channel_to_plot_arb_data.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox_TD_channel_to_plot_arb_data)
        self.pushButton_choose_folder_to_process = QtWidgets.QPushButton(self.page_processing)
        self.pushButton_choose_folder_to_process.setGeometry(QtCore.QRect(10, 0, 63, 23))
        self.pushButton_choose_folder_to_process.setObjectName("pushButton_choose_folder_to_process")
        self.label_folder_to_process_files = QtWidgets.QLabel(self.page_processing)
        self.label_folder_to_process_files.setGeometry(QtCore.QRect(90, 0, 201, 16))
        self.label_folder_to_process_files.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_folder_to_process_files.setObjectName("label_folder_to_process_files")
        self.Toolbox.addItem(self.page_processing, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 283, 600))
        self.page_3.setMinimumSize(QtCore.QSize(0, 600))
        self.page_3.setObjectName("page_3")
        self.groupBox = QtWidgets.QGroupBox(self.page_3)
        self.groupBox.setGeometry(QtCore.QRect(0, 80, 281, 261))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_analyzer_plot2D = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_analyzer_plot2D.setGeometry(QtCore.QRect(10, 20, 111, 23))
        self.pushButton_analyzer_plot2D.setObjectName("pushButton_analyzer_plot2D")
        self.pushButton_analyzer_plotSampleShape = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_analyzer_plotSampleShape.setGeometry(QtCore.QRect(10, 80, 111, 23))
        self.pushButton_analyzer_plotSampleShape.setObjectName("pushButton_analyzer_plotSampleShape")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 200, 281, 51))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton_analyzer_plotSlice = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_analyzer_plotSlice.setGeometry(QtCore.QRect(10, 20, 75, 23))
        self.pushButton_analyzer_plotSlice.setObjectName("pushButton_analyzer_plotSlice")
        self.lineEdit_slice_position = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_slice_position.setGeometry(QtCore.QRect(100, 20, 41, 21))
        self.lineEdit_slice_position.setObjectName("lineEdit_slice_position")
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(150, 20, 91, 16))
        self.label_14.setObjectName("label_14")
        self.comboBox_axis_to_analyze_along_arb_data = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_axis_to_analyze_along_arb_data.setGeometry(QtCore.QRect(240, 20, 33, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_axis_to_analyze_along_arb_data.sizePolicy().hasHeightForWidth())
        self.comboBox_axis_to_analyze_along_arb_data.setSizePolicy(sizePolicy)
        self.comboBox_axis_to_analyze_along_arb_data.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_axis_to_analyze_along_arb_data.setObjectName("comboBox_axis_to_analyze_along_arb_data")
        self.comboBox_axis_to_analyze_along_arb_data.addItem("")
        self.comboBox_axis_to_analyze_along_arb_data.addItem("")
        self.comboBox_axis_to_analyze_along_arb_data.addItem("")
        self.pushButton_analyzer_choose_plotting_param_file = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_analyzer_choose_plotting_param_file.setGeometry(QtCore.QRect(10, 50, 111, 23))
        self.pushButton_analyzer_choose_plotting_param_file.setObjectName("pushButton_analyzer_choose_plotting_param_file")
        self.pushButton_analyzer_extract_ERV = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_analyzer_extract_ERV.setGeometry(QtCore.QRect(10, 110, 111, 21))
        self.pushButton_analyzer_extract_ERV.setObjectName("pushButton_analyzer_extract_ERV")
        self.pushButton_analyzer_apply_FFT_filter = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_analyzer_apply_FFT_filter.setGeometry(QtCore.QRect(140, 80, 131, 21))
        self.pushButton_analyzer_apply_FFT_filter.setObjectName("pushButton_analyzer_apply_FFT_filter")
        self.pushButton_analyzer_plot_ERV_from_file = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_analyzer_plot_ERV_from_file.setGeometry(QtCore.QRect(140, 110, 131, 21))
        self.pushButton_analyzer_plot_ERV_from_file.setObjectName("pushButton_analyzer_plot_ERV_from_file")
        self.pushButton_analyzer_resave_SNAP = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_analyzer_resave_SNAP.setGeometry(QtCore.QRect(10, 170, 111, 21))
        self.pushButton_analyzer_resave_SNAP.setObjectName("pushButton_analyzer_resave_SNAP")
        self.comboBox_analyzer_resave_type = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_analyzer_resave_type.setGeometry(QtCore.QRect(200, 170, 69, 22))
        self.comboBox_analyzer_resave_type.setObjectName("comboBox_analyzer_resave_type")
        self.comboBox_analyzer_resave_type.addItem("")
        self.comboBox_analyzer_resave_type.addItem("")
        self.comboBox_analyzer_resave_type.addItem("")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(137, 175, 47, 13))
        self.label_3.setObjectName("label_3")
        self.groupBox_8 = QtWidgets.QGroupBox(self.page_3)
        self.groupBox_8.setGeometry(QtCore.QRect(0, 350, 281, 181))
        self.groupBox_8.setObjectName("groupBox_8")
        self.pushButton_analyzer_choose_single_spectrum = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_analyzer_choose_single_spectrum.setGeometry(QtCore.QRect(20, 20, 100, 23))
        self.pushButton_analyzer_choose_single_spectrum.setObjectName("pushButton_analyzer_choose_single_spectrum")
        self.label_analyzer_single_spectrum_file = QtWidgets.QLabel(self.groupBox_8)
        self.label_analyzer_single_spectrum_file.setGeometry(QtCore.QRect(150, 20, 121, 23))
        self.label_analyzer_single_spectrum_file.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_analyzer_single_spectrum_file.setObjectName("label_analyzer_single_spectrum_file")
        self.pushButton_analyzer_plot_single_spectrum = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_analyzer_plot_single_spectrum.setGeometry(QtCore.QRect(20, 50, 101, 23))
        self.pushButton_analyzer_plot_single_spectrum.setObjectName("pushButton_analyzer_plot_single_spectrum")
        self.pushButton_analyzer_save_single_spectrum = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_analyzer_save_single_spectrum.setGeometry(QtCore.QRect(20, 80, 101, 23))
        self.pushButton_analyzer_save_single_spectrum.setObjectName("pushButton_analyzer_save_single_spectrum")
        self.pushButton_analyzer_analyze_spectrum = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_analyzer_analyze_spectrum.setGeometry(QtCore.QRect(20, 110, 101, 23))
        self.pushButton_analyzer_analyze_spectrum.setObjectName("pushButton_analyzer_analyze_spectrum")
        self.pushButton_analyzer_quantum_numbers_fitter = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_analyzer_quantum_numbers_fitter.setGeometry(QtCore.QRect(20, 140, 101, 23))
        self.pushButton_analyzer_quantum_numbers_fitter.setObjectName("pushButton_analyzer_quantum_numbers_fitter")
        self.pushButton_set_analyzer_parameters = QtWidgets.QPushButton(self.page_3)
        self.pushButton_set_analyzer_parameters.setGeometry(QtCore.QRect(10, 10, 151, 21))
        self.pushButton_set_analyzer_parameters.setObjectName("pushButton_set_analyzer_parameters")
        self.pushButton_analyzer_choose_file_spectrogram = QtWidgets.QPushButton(self.page_3)
        self.pushButton_analyzer_choose_file_spectrogram.setGeometry(QtCore.QRect(10, 50, 151, 23))
        self.pushButton_analyzer_choose_file_spectrogram.setObjectName("pushButton_analyzer_choose_file_spectrogram")
        self.label_analyzer_file = QtWidgets.QLabel(self.page_3)
        self.label_analyzer_file.setGeometry(QtCore.QRect(170, 50, 101, 23))
        self.label_analyzer_file.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_analyzer_file.setObjectName("label_analyzer_file")
        self.Toolbox.addItem(self.page_3, "")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 283, 500))
        self.page_6.setMinimumSize(QtCore.QSize(0, 500))
        self.page_6.setObjectName("page_6")
        self.groupBox_laser_scanning = QtWidgets.QGroupBox(self.page_6)
        self.groupBox_laser_scanning.setEnabled(True)
        self.groupBox_laser_scanning.setGeometry(QtCore.QRect(0, 150, 281, 161))
        self.groupBox_laser_scanning.setObjectName("groupBox_laser_scanning")
        self.lineEdit_laser_scanning_max_detuning = QtWidgets.QLineEdit(self.groupBox_laser_scanning)
        self.lineEdit_laser_scanning_max_detuning.setGeometry(QtCore.QRect(10, 50, 91, 20))
        self.lineEdit_laser_scanning_max_detuning.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_laser_scanning_max_detuning.setObjectName("lineEdit_laser_scanning_max_detuning")
        self.label_18 = QtWidgets.QLabel(self.groupBox_laser_scanning)
        self.label_18.setGeometry(QtCore.QRect(0, 20, 121, 21))
        self.label_18.setObjectName("label_18")
        self.lineEdit_laser_lambda_scanning_step = QtWidgets.QLineEdit(self.groupBox_laser_scanning)
        self.lineEdit_laser_lambda_scanning_step.setEnabled(True)
        self.lineEdit_laser_lambda_scanning_step.setGeometry(QtCore.QRect(110, 50, 81, 20))
        self.lineEdit_laser_lambda_scanning_step.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_laser_lambda_scanning_step.setObjectName("lineEdit_laser_lambda_scanning_step")
        self.label_19 = QtWidgets.QLabel(self.groupBox_laser_scanning)
        self.label_19.setGeometry(QtCore.QRect(110, 22, 111, 21))
        self.label_19.setObjectName("label_19")
        self.pushButton_scan_laser_wavelength = QtWidgets.QPushButton(self.groupBox_laser_scanning)
        self.pushButton_scan_laser_wavelength.setEnabled(False)
        self.pushButton_scan_laser_wavelength.setGeometry(QtCore.QRect(200, 50, 75, 23))
        self.pushButton_scan_laser_wavelength.setCheckable(True)
        self.pushButton_scan_laser_wavelength.setObjectName("pushButton_scan_laser_wavelength")
        self.checkBox_OSA_for_laser_scanning = QtWidgets.QCheckBox(self.groupBox_laser_scanning)
        self.checkBox_OSA_for_laser_scanning.setEnabled(True)
        self.checkBox_OSA_for_laser_scanning.setGeometry(QtCore.QRect(160, 80, 81, 20))
        self.checkBox_OSA_for_laser_scanning.setChecked(False)
        self.checkBox_OSA_for_laser_scanning.setObjectName("checkBox_OSA_for_laser_scanning")
        self.checkBox_powermeter_for_laser_scanning = QtWidgets.QCheckBox(self.groupBox_laser_scanning)
        self.checkBox_powermeter_for_laser_scanning.setEnabled(True)
        self.checkBox_powermeter_for_laser_scanning.setGeometry(QtCore.QRect(160, 110, 111, 20))
        self.checkBox_powermeter_for_laser_scanning.setChecked(False)
        self.checkBox_powermeter_for_laser_scanning.setObjectName("checkBox_powermeter_for_laser_scanning")
        self.pushButton_hold_laser_wavelength = QtWidgets.QPushButton(self.groupBox_laser_scanning)
        self.pushButton_hold_laser_wavelength.setEnabled(True)
        self.pushButton_hold_laser_wavelength.setGeometry(QtCore.QRect(200, 130, 75, 23))
        self.pushButton_hold_laser_wavelength.setCheckable(True)
        self.pushButton_hold_laser_wavelength.setObjectName("pushButton_hold_laser_wavelength")
        self.groupBox_laser_operation = QtWidgets.QGroupBox(self.page_6)
        self.groupBox_laser_operation.setEnabled(True)
        self.groupBox_laser_operation.setGeometry(QtCore.QRect(0, 20, 281, 121))
        self.groupBox_laser_operation.setObjectName("groupBox_laser_operation")
        self.lineEdit_laser_lambda = QtWidgets.QLineEdit(self.groupBox_laser_operation)
        self.lineEdit_laser_lambda.setEnabled(True)
        self.lineEdit_laser_lambda.setGeometry(QtCore.QRect(10, 40, 71, 20))
        self.lineEdit_laser_lambda.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_laser_lambda.setObjectName("lineEdit_laser_lambda")
        self.lineEdit_laser_power = QtWidgets.QLineEdit(self.groupBox_laser_operation)
        self.lineEdit_laser_power.setGeometry(QtCore.QRect(90, 40, 41, 20))
        self.lineEdit_laser_power.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_laser_power.setObjectName("lineEdit_laser_power")
        self.label_21 = QtWidgets.QLabel(self.groupBox_laser_operation)
        self.label_21.setGeometry(QtCore.QRect(80, 20, 71, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_laser_operation)
        self.label_22.setGeometry(QtCore.QRect(10, 20, 47, 13))
        self.label_22.setObjectName("label_22")
        self.pushButton_laser_On = QtWidgets.QPushButton(self.groupBox_laser_operation)
        self.pushButton_laser_On.setEnabled(False)
        self.pushButton_laser_On.setGeometry(QtCore.QRect(210, 40, 61, 23))
        self.pushButton_laser_On.setCheckable(True)
        self.pushButton_laser_On.setChecked(False)
        self.pushButton_laser_On.setObjectName("pushButton_laser_On")
        self.lineEdit_laser_fine_tune = QtWidgets.QLineEdit(self.groupBox_laser_operation)
        self.lineEdit_laser_fine_tune.setEnabled(False)
        self.lineEdit_laser_fine_tune.setGeometry(QtCore.QRect(10, 90, 61, 20))
        self.lineEdit_laser_fine_tune.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_laser_fine_tune.setObjectName("lineEdit_laser_fine_tune")
        self.label_23 = QtWidgets.QLabel(self.groupBox_laser_operation)
        self.label_23.setGeometry(QtCore.QRect(0, 70, 91, 20))
        self.label_23.setObjectName("label_23")
        self.comboBox_laser_mode = QtWidgets.QComboBox(self.groupBox_laser_operation)
        self.comboBox_laser_mode.setEnabled(False)
        self.comboBox_laser_mode.setGeometry(QtCore.QRect(140, 40, 61, 22))
        self.comboBox_laser_mode.setEditable(False)
        self.comboBox_laser_mode.setObjectName("comboBox_laser_mode")
        self.comboBox_laser_mode.addItem("")
        self.comboBox_laser_mode.addItem("")
        self.comboBox_laser_mode.addItem("")
        self.label_25 = QtWidgets.QLabel(self.groupBox_laser_operation)
        self.label_25.setGeometry(QtCore.QRect(140, 20, 61, 16))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.label_20 = QtWidgets.QLabel(self.groupBox_laser_operation)
        self.label_20.setGeometry(QtCore.QRect(110, 70, 151, 21))
        self.label_20.setObjectName("label_20")
        self.label_current_laser_wavelength = QtWidgets.QLabel(self.groupBox_laser_operation)
        self.label_current_laser_wavelength.setEnabled(True)
        self.label_current_laser_wavelength.setGeometry(QtCore.QRect(110, 90, 121, 21))
        self.label_current_laser_wavelength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_current_laser_wavelength.setObjectName("label_current_laser_wavelength")
        self.groupBox_laser_sweeping = QtWidgets.QGroupBox(self.page_6)
        self.groupBox_laser_sweeping.setEnabled(False)
        self.groupBox_laser_sweeping.setGeometry(QtCore.QRect(0, 320, 281, 121))
        self.groupBox_laser_sweeping.setObjectName("groupBox_laser_sweeping")
        self.lineEdit_laser_lambda_sweeping_central = QtWidgets.QLineEdit(self.groupBox_laser_sweeping)
        self.lineEdit_laser_lambda_sweeping_central.setGeometry(QtCore.QRect(30, 50, 61, 20))
        self.lineEdit_laser_lambda_sweeping_central.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_laser_lambda_sweeping_central.setObjectName("lineEdit_laser_lambda_sweeping_central")
        self.lineEdit_laser_sweeping_max_detuning = QtWidgets.QLineEdit(self.groupBox_laser_sweeping)
        self.lineEdit_laser_sweeping_max_detuning.setGeometry(QtCore.QRect(110, 50, 61, 20))
        self.lineEdit_laser_sweeping_max_detuning.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_laser_sweeping_max_detuning.setObjectName("lineEdit_laser_sweeping_max_detuning")
        self.label_26 = QtWidgets.QLabel(self.groupBox_laser_sweeping)
        self.label_26.setGeometry(QtCore.QRect(36, 22, 61, 21))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_laser_sweeping)
        self.label_27.setGeometry(QtCore.QRect(130, 22, 47, 21))
        self.label_27.setObjectName("label_27")
        self.lineEdit_laser_lambda_sweeping_step = QtWidgets.QLineEdit(self.groupBox_laser_sweeping)
        self.lineEdit_laser_lambda_sweeping_step.setGeometry(QtCore.QRect(180, 50, 41, 20))
        self.lineEdit_laser_lambda_sweeping_step.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_laser_lambda_sweeping_step.setObjectName("lineEdit_laser_lambda_sweeping_step")
        self.label_28 = QtWidgets.QLabel(self.groupBox_laser_sweeping)
        self.label_28.setGeometry(QtCore.QRect(185, 23, 47, 21))
        self.label_28.setObjectName("label_28")
        self.pushButton_sweep_laser_wavelength = QtWidgets.QPushButton(self.groupBox_laser_sweeping)
        self.pushButton_sweep_laser_wavelength.setGeometry(QtCore.QRect(200, 90, 75, 23))
        self.pushButton_sweep_laser_wavelength.setCheckable(True)
        self.pushButton_sweep_laser_wavelength.setObjectName("pushButton_sweep_laser_wavelength")
        self.lineEdit_laser_lambda_sweeping_delay = QtWidgets.QLineEdit(self.groupBox_laser_sweeping)
        self.lineEdit_laser_lambda_sweeping_delay.setGeometry(QtCore.QRect(230, 50, 41, 20))
        self.lineEdit_laser_lambda_sweeping_delay.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_laser_lambda_sweeping_delay.setObjectName("lineEdit_laser_lambda_sweeping_delay")
        self.label_30 = QtWidgets.QLabel(self.groupBox_laser_sweeping)
        self.label_30.setGeometry(QtCore.QRect(230, 23, 47, 21))
        self.label_30.setObjectName("label_30")
        self.Toolbox.addItem(self.page_6, "")
        self.gridLayout_4.addWidget(self.Toolbox, 0, 1, 2, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1183, 21))
        self.menubar.setObjectName("menubar")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuData = QtWidgets.QMenu(self.menubar)
        self.menuData.setObjectName("menuData")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_save_parameters = QtWidgets.QAction(MainWindow)
        self.action_save_parameters.setObjectName("action_save_parameters")
        self.action_load_parameters = QtWidgets.QAction(MainWindow)
        self.action_load_parameters.setObjectName("action_load_parameters")
        self.action_delete_all_figures = QtWidgets.QAction(MainWindow)
        self.action_delete_all_figures.setObjectName("action_delete_all_figures")
        self.action_delete_all_measured_spectral_data = QtWidgets.QAction(MainWindow)
        self.action_delete_all_measured_spectral_data.setObjectName("action_delete_all_measured_spectral_data")
        self.menuTools.addAction(self.action_save_parameters)
        self.menuTools.addAction(self.action_load_parameters)
        self.menuTools.addAction(self.action_delete_all_figures)
        self.menuData.addAction(self.action_delete_all_measured_spectral_data)
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuData.menuAction())

        self.retranslateUi(MainWindow)
        self.Toolbox.setCurrentIndex(3)
        self.tabWidget_instruments.setCurrentIndex(0)
        self.comboBox_axis_to_analyze_along_arb_data.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Range, nm"))
        self.lineEdit_StartWavelength.setText(_translate("MainWindow", "1550"))
        self.lineEdit_StopWavelength.setText(_translate("MainWindow", "1551.123"))
        self.pushButton_getRange.setText(_translate("MainWindow", "Get range"))
        self.checkBox_FreezeSpectrum.setText(_translate("MainWindow", "Freeze"))
        self.pushButton_set_max_OSA_range.setText(_translate("MainWindow", "Set MAX range"))
        self.groupBox_11.setTitle(_translate("MainWindow", "FFT filter"))
        self.lineEdit_FilterLowFreqEdge.setText(_translate("MainWindow", "0.00001"))
        self.lineEdit_FilterHighFreqEdge.setText(_translate("MainWindow", "0.01"))
        self.checkBox_ApplyFFTFilter.setText(_translate("MainWindow", "Apply"))
        self.lineEdit_FilterPointsToCut.setText(_translate("MainWindow", "100"))
        self.groupBox_spectrum.setToolTip(_translate("MainWindow", "10", "Plot results on new figures"))
        self.groupBox_spectrum.setTitle(_translate("MainWindow", "Graph"))
        self.label_analyzer_plotting_file.setText(_translate("MainWindow", "none"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Equipment"))
        self.pushButton_StagesConnect.setText(_translate("MainWindow", "Stages"))
        self.pushButton_scope_connect.setText(_translate("MainWindow", "Oscilloscope"))
        self.pushButton_laser_connect.setText(_translate("MainWindow", "Laser Pure Ph"))
        self.comboBox_Type_of_Stages.setItemText(0, _translate("MainWindow", "3x Standa"))
        self.comboBox_Type_of_Stages.setItemText(1, _translate("MainWindow", "2x Thorlabs"))
        self.comboBox_Type_of_Stages.setItemText(2, _translate("MainWindow", "3x Physik Instrumente"))
        self.lineEdit_laser_COMport.setText(_translate("MainWindow", "8"))
        self.label_24.setText(_translate("MainWindow", "Com port"))
        self.pushButton_zeroing_stages.setText(_translate("MainWindow", "Zeroing"))
        self.groupBox_features.setTitle(_translate("MainWindow", "OSA"))
        self.label_29.setText(_translate("MainWindow", "APEX mode"))
        self.comboBox_Luna_mode.setItemText(0, _translate("MainWindow", "pkl files"))
        self.comboBox_Luna_mode.setItemText(1, _translate("MainWindow", "Luna .bin files"))
        self.label_Luna_mode.setText(_translate("MainWindow", "Luna mode"))
        self.comboBox_APEX_mode.setItemText(0, _translate("MainWindow", "OSA"))
        self.comboBox_APEX_mode.setItemText(1, _translate("MainWindow", "Tracking generator"))
        self.comboBox_Type_of_OSA.setItemText(0, _translate("MainWindow", "APEX"))
        self.comboBox_Type_of_OSA.setItemText(1, _translate("MainWindow", "Luna"))
        self.comboBox_Type_of_OSA.setItemText(2, _translate("MainWindow", "Yokogawa"))
        self.comboBox_Type_of_OSA.setItemText(3, _translate("MainWindow", "Astro interrogator"))
        self.pushButton_OSA_connect.setText(_translate("MainWindow", "OSA"))
        self.pushButton_powermeter_connect.setText(_translate("MainWindow", "Powermeter PM"))
        self.pushButton_powermeter_graph.setText(_translate("MainWindow", "PM graph"))
        self.Toolbox.setItemText(self.Toolbox.indexOf(self.page), _translate("MainWindow", "Hardware control"))
        self.label.setText(_translate("MainWindow", "Set channel"))
        self.comboBox_interrogatorChannel.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_interrogatorChannel.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_interrogatorChannel.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_interrogatorChannel.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_interrogatorChannel.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox_interrogatorChannel.setItemText(5, _translate("MainWindow", "5"))
        self.comboBox_interrogatorChannel.setItemText(6, _translate("MainWindow", "6"))
        self.comboBox_interrogatorChannel.setItemText(7, _translate("MainWindow", "7"))
        self.pushButton_OSA_Acquire.setText(_translate("MainWindow", "Single"))
        self.pushButton_OSA_AcquireRep.setText(_translate("MainWindow", "Repeat"))
        self.checkBox_HighRes.setText(_translate("MainWindow", "High res"))
        self.pushButton_OSA_AcquireAll.setText(_translate("MainWindow", "Single All"))
        self.tabWidget_instruments.setTabText(self.tabWidget_instruments.indexOf(self.groupBox_OSA_control), _translate("MainWindow", "OSA"))
        self.pushButton_scope_repeat.setText(_translate("MainWindow", "Repeat"))
        self.pushButton_scope_single.setText(_translate("MainWindow", "Single"))
        self.label_10.setText(_translate("MainWindow", "Channels"))
        self.checkBox_ScopeCh1.setText(_translate("MainWindow", "1"))
        self.checkBox_ScopeCh2.setText(_translate("MainWindow", "2"))
        self.checkBox_ScopeCh3.setText(_translate("MainWindow", "3"))
        self.checkBox_ScopeCh4.setText(_translate("MainWindow", "4"))
        self.tabWidget_instruments.setTabText(self.tabWidget_instruments.indexOf(self.groupBox_scope_control), _translate("MainWindow", "Scope"))
        self.groupBox_stand.setTitle(_translate("MainWindow", "Stages control, in microns"))
        self.pushButton_MoveMinusX.setText(_translate("MainWindow", "-X"))
        self.pushButton_MovePlusY.setText(_translate("MainWindow", "+Y"))
        self.pushButton_MoveMinusZ.setText(_translate("MainWindow", "-Z"))
        self.lineEdit_StepZ.setText(_translate("MainWindow", "40"))
        self.pushButton_MovePlusZ.setText(_translate("MainWindow", "+Z"))
        self.pushButton_MovePlusX.setText(_translate("MainWindow", "+X"))
        self.lineEdit_StepY.setText(_translate("MainWindow", "40"))
        self.pushButton_MoveMinusY.setText(_translate("MainWindow", "-Y"))
        self.lineEdit_StepX.setText(_translate("MainWindow", "40"))
        self.label_PositionZ.setText(_translate("MainWindow", "0"))
        self.label_AbsPositionX.setText(_translate("MainWindow", "0"))
        self.pushButton_zeroingPositions.setText(_translate("MainWindow", "Zeroing positions"))
        self.label_PositionY.setText(_translate("MainWindow", "0"))
        self.label_PositionX.setText(_translate("MainWindow", "0"))
        self.label_AbsPositionY.setText(_translate("MainWindow", "0"))
        self.label_AbsPositionZ.setText(_translate("MainWindow", "0"))
        self.label_11.setText(_translate("MainWindow", "Rel.pos."))
        self.label_12.setText(_translate("MainWindow", "Abs.pos."))
        self.groupBox_save_data.setTitle(_translate("MainWindow", "Tools"))
        self.lineEdit_saveSpectrumName.setText(_translate("MainWindow", "File Name"))
        self.pushButton_save_data.setText(_translate("MainWindow", "Save data"))
        self.pushButton_processTDData.setText(_translate("MainWindow", "Process TD"))
        self.pushButton_process_measured_spectral_data.setToolTip(_translate("MainWindow", "Process spectra"))
        self.pushButton_process_measured_spectral_data.setText(_translate("MainWindow", "Process spectra"))
        self.comboBox_TD_channel_to_plot.setToolTip(_translate("MainWindow", "Choose channel to plot"))
        self.comboBox_TD_channel_to_plot.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_TD_channel_to_plot.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_TD_channel_to_plot.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_TD_channel_to_plot.setItemText(3, _translate("MainWindow", "4"))
        self.pushButton_plotSampleShape.setText(_translate("MainWindow", "Plot sample shape"))
        self.pushButton_set_spectral_processor_parameters_2.setText(_translate("MainWindow", "Processing parameters"))
        self.pushButton_analyze_spectrum.setText(_translate("MainWindow", "Analyze spectrum"))
        self.groupBox_Scanning.setTitle(_translate("MainWindow", "Scanning"))
        self.pushButton_scan_in_space.setText(_translate("MainWindow", "Scanning"))
        self.pushButton_set_scanning_parameters.setText(_translate("MainWindow", "Scanning parameters"))
        self.label_scanning_index_status.setText(_translate("MainWindow", "Step __ of __"))
        self.label_scanning_axis.setText(_translate("MainWindow", "__"))
        self.label_scanning_final_position.setText(_translate("MainWindow", "_______"))
        self.label_2.setText(_translate("MainWindow", "Scan along __, final position _______ microns"))
        self.Toolbox.setItemText(self.Toolbox.indexOf(self.page_2), _translate("MainWindow", "Experiment\'s flow"))
        self.groupBox_processArbData.setTitle(_translate("MainWindow", "Process raw spectra filed"))
        self.pushButton_process_arb_spectral_data.setText(_translate("MainWindow", "Process spectra from raw data"))
        self.pushButton_plotSampleShape_arb_data.setText(_translate("MainWindow", "Plot sample shape"))
        self.pushButton_set_spectral_processor_parameters.setText(_translate("MainWindow", "Parameters"))
        self.groupBox_processArbData_2.setTitle(_translate("MainWindow", "Process time dynamics"))
        self.pushButton_process_arb_TD_data.setText(_translate("MainWindow", "Process time dinamics from raw data"))
        self.label_31.setText(_translate("MainWindow", "Channel number"))
        self.comboBox_TD_channel_to_plot_arb_data.setToolTip(_translate("MainWindow", "Choose channel to plot"))
        self.comboBox_TD_channel_to_plot_arb_data.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_TD_channel_to_plot_arb_data.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_TD_channel_to_plot_arb_data.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_TD_channel_to_plot_arb_data.setItemText(3, _translate("MainWindow", "4"))
        self.pushButton_choose_folder_to_process.setText(_translate("MainWindow", "Folder"))
        self.label_folder_to_process_files.setText(_translate("MainWindow", "none"))
        self.Toolbox.setItemText(self.Toolbox.indexOf(self.page_processing), _translate("MainWindow", "Processing raw data"))
        self.groupBox.setTitle(_translate("MainWindow", "Analyze spectrogram"))
        self.pushButton_analyzer_plot2D.setText(_translate("MainWindow", "Plot 2D"))
        self.pushButton_analyzer_plotSampleShape.setText(_translate("MainWindow", "Plot sample shape"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Plot slice"))
        self.pushButton_analyzer_plotSlice.setText(_translate("MainWindow", "Plot slice at"))
        self.lineEdit_slice_position.setText(_translate("MainWindow", "500"))
        self.label_14.setText(_translate("MainWindow", "microns along axis"))
        self.comboBox_axis_to_analyze_along_arb_data.setToolTip(_translate("MainWindow", "Choose channel to plot"))
        self.comboBox_axis_to_analyze_along_arb_data.setItemText(0, _translate("MainWindow", "X"))
        self.comboBox_axis_to_analyze_along_arb_data.setItemText(1, _translate("MainWindow", "Y"))
        self.comboBox_axis_to_analyze_along_arb_data.setItemText(2, _translate("MainWindow", "Z"))
        self.pushButton_analyzer_choose_plotting_param_file.setText(_translate("MainWindow", "Plotting param file "))
        self.pushButton_analyzer_extract_ERV.setText(_translate("MainWindow", "Get ERV(z)"))
        self.pushButton_analyzer_apply_FFT_filter.setText(_translate("MainWindow", "Apply FFT filter"))
        self.pushButton_analyzer_plot_ERV_from_file.setText(_translate("MainWindow", "Load ERV from file"))
        self.pushButton_analyzer_resave_SNAP.setText(_translate("MainWindow", "Resave spectrogram "))
        self.comboBox_analyzer_resave_type.setItemText(0, _translate("MainWindow", "SNAP"))
        self.comboBox_analyzer_resave_type.setItemText(1, _translate("MainWindow", "cSNAP"))
        self.comboBox_analyzer_resave_type.setItemText(2, _translate("MainWindow", "pkl3d"))
        self.label_3.setText(_translate("MainWindow", "as"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Single spectrum"))
        self.pushButton_analyzer_choose_single_spectrum.setText(_translate("MainWindow", "Spectrum file"))
        self.label_analyzer_single_spectrum_file.setText(_translate("MainWindow", "none"))
        self.pushButton_analyzer_plot_single_spectrum.setText(_translate("MainWindow", "Plot"))
        self.pushButton_analyzer_save_single_spectrum.setText(_translate("MainWindow", "Save/Resave"))
        self.pushButton_analyzer_analyze_spectrum.setText(_translate("MainWindow", "Fit Lorenzian"))
        self.pushButton_analyzer_quantum_numbers_fitter.setText(_translate("MainWindow", "Quantum numbers"))
        self.pushButton_set_analyzer_parameters.setText(_translate("MainWindow", "Analyzer parameters"))
        self.pushButton_analyzer_choose_file_spectrogram.setText(_translate("MainWindow", "Spectrogram file"))
        self.label_analyzer_file.setText(_translate("MainWindow", "none"))
        self.Toolbox.setItemText(self.Toolbox.indexOf(self.page_3), _translate("MainWindow", "Analyzer"))
        self.groupBox_laser_scanning.setTitle(_translate("MainWindow", "Scanning wavelength and save data "))
        self.lineEdit_laser_scanning_max_detuning.setText(_translate("MainWindow", "200"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p>Max detuning, pm</p></body></html>"))
        self.lineEdit_laser_lambda_scanning_step.setText(_translate("MainWindow", "0.1"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p>detuning step, pm</p></body></html>"))
        self.pushButton_scan_laser_wavelength.setText(_translate("MainWindow", "Scanning"))
        self.checkBox_OSA_for_laser_scanning.setText(_translate("MainWindow", "save OSA"))
        self.checkBox_powermeter_for_laser_scanning.setText(_translate("MainWindow", "save powermeter"))
        self.pushButton_hold_laser_wavelength.setText(_translate("MainWindow", "Hold"))
        self.groupBox_laser_operation.setTitle(_translate("MainWindow", "Laser operation"))
        self.lineEdit_laser_lambda.setText(_translate("MainWindow", "1550.000"))
        self.lineEdit_laser_power.setText(_translate("MainWindow", "1000"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p>P, dBm*100</p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p>?, nm</p></body></html>"))
        self.pushButton_laser_On.setText(_translate("MainWindow", "Laser On"))
        self.lineEdit_laser_fine_tune.setText(_translate("MainWindow", "0"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p>Fine tune, pm</p></body></html>"))
        self.comboBox_laser_mode.setItemText(0, _translate("MainWindow", "Dither"))
        self.comboBox_laser_mode.setItemText(1, _translate("MainWindow", "Nodither"))
        self.comboBox_laser_mode.setItemText(2, _translate("MainWindow", "Whisper"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p>Mode</p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p>Actual wavelength, nm</p></body></html>"))
        self.label_current_laser_wavelength.setText(_translate("MainWindow", "<html><head/><body><p>1550.00000</p></body></html>"))
        self.groupBox_laser_sweeping.setTitle(_translate("MainWindow", "Sweeping wavelength fast"))
        self.lineEdit_laser_lambda_sweeping_central.setText(_translate("MainWindow", "1550"))
        self.lineEdit_laser_sweeping_max_detuning.setText(_translate("MainWindow", "100"))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p>?<span style=\" vertical-align:sub;\">central</span>, nm</p></body></html>"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p>D?, pm</p></body></html>"))
        self.lineEdit_laser_lambda_sweeping_step.setText(_translate("MainWindow", "1"))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p>d?, pm</p></body></html>"))
        self.pushButton_sweep_laser_wavelength.setText(_translate("MainWindow", "Sweeping"))
        self.lineEdit_laser_lambda_sweeping_delay.setText(_translate("MainWindow", "0"))
        self.label_30.setText(_translate("MainWindow", "<html><head/><body><p>delay, s</p></body></html>"))
        self.Toolbox.setItemText(self.Toolbox.indexOf(self.page_6), _translate("MainWindow", "Laser control"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuData.setTitle(_translate("MainWindow", "Data"))
        self.action_save_parameters.setText(_translate("MainWindow", "&Save parameters"))
        self.action_save_parameters.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_load_parameters.setText(_translate("MainWindow", "&Load parameters"))
        self.action_load_parameters.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.action_delete_all_figures.setText(_translate("MainWindow", "Delete all figures"))
        self.action_delete_all_figures.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.action_delete_all_measured_spectral_data.setText(_translate("MainWindow", "Delete all measured spectral data"))
        self.action_delete_all_measured_spectral_data.setToolTip(_translate("MainWindow", "Delete all measured spectral data in SpetralData and SpectralBinData folders"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

