# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scanning_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(559, 258)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(490, 30, 61, 201))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox_Scanning = QtWidgets.QGroupBox(Dialog)
        self.groupBox_Scanning.setEnabled(True)
        self.groupBox_Scanning.setGeometry(QtCore.QRect(10, 20, 471, 231))
        self.groupBox_Scanning.setObjectName("groupBox_Scanning")
        self.label_4 = QtWidgets.QLabel(self.groupBox_Scanning)
        self.label_4.setGeometry(QtCore.QRect(10, 49, 64, 39))
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_Scanning)
        self.label_5.setGeometry(QtCore.QRect(80, 49, 63, 39))
        self.label_5.setScaledContents(False)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.lineEdit_current_file_index = QtWidgets.QLineEdit(self.groupBox_Scanning)
        self.lineEdit_current_file_index.setGeometry(QtCore.QRect(50, 160, 31, 20))
        self.lineEdit_current_file_index.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_current_file_index.setObjectName("lineEdit_current_file_index")
        self.label_8 = QtWidgets.QLabel(self.groupBox_Scanning)
        self.label_8.setGeometry(QtCore.QRect(10, 160, 34, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_seeking_step = QtWidgets.QLineEdit(self.groupBox_Scanning)
        self.lineEdit_seeking_step.setGeometry(QtCore.QRect(80, 94, 63, 20))
        self.lineEdit_seeking_step.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_seeking_step.setObjectName("lineEdit_seeking_step")
        self.lineEdit_scanning_step = QtWidgets.QLineEdit(self.groupBox_Scanning)
        self.lineEdit_scanning_step.setGeometry(QtCore.QRect(10, 94, 64, 20))
        self.lineEdit_scanning_step.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_scanning_step.setObjectName("lineEdit_scanning_step")
        self.comboBox_scanning_type = QtWidgets.QComboBox(self.groupBox_Scanning)
        self.comboBox_scanning_type.setGeometry(QtCore.QRect(10, 23, 201, 20))
        self.comboBox_scanning_type.setObjectName("comboBox_scanning_type")
        self.comboBox_scanning_type.addItem("")
        self.comboBox_scanning_type.addItem("")
        self.comboBox_scanning_type.addItem("")
        self.comboBox_scanning_type.addItem("")
        self.comboBox_scanning_type.addItem("")
        self.lineEdit_stop_file_index = QtWidgets.QLineEdit(self.groupBox_Scanning)
        self.lineEdit_stop_file_index.setGeometry(QtCore.QRect(110, 160, 41, 20))
        self.lineEdit_stop_file_index.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_stop_file_index.setObjectName("lineEdit_stop_file_index")
        self.label_2 = QtWidgets.QLabel(self.groupBox_Scanning)
        self.label_2.setGeometry(QtCore.QRect(90, 160, 16, 16))
        self.label_2.setObjectName("label_2")
        self.checkBox_save_out_of_contact = QtWidgets.QCheckBox(self.groupBox_Scanning)
        self.checkBox_save_out_of_contact.setGeometry(QtCore.QRect(160, 150, 101, 17))
        self.checkBox_save_out_of_contact.setObjectName("checkBox_save_out_of_contact")
        self.checkBox_is_seeking_contact = QtWidgets.QCheckBox(self.groupBox_Scanning)
        self.checkBox_is_seeking_contact.setEnabled(True)
        self.checkBox_is_seeking_contact.setGeometry(QtCore.QRect(160, 96, 111, 17))
        self.checkBox_is_seeking_contact.setChecked(True)
        self.checkBox_is_seeking_contact.setObjectName("checkBox_is_seeking_contact")
        self.label_3 = QtWidgets.QLabel(self.groupBox_Scanning)
        self.label_3.setGeometry(QtCore.QRect(10, 128, 31, 28))
        self.label_3.setObjectName("label_3")
        self.lineEdit_number_of_scans_at_point = QtWidgets.QLineEdit(self.groupBox_Scanning)
        self.lineEdit_number_of_scans_at_point.setGeometry(QtCore.QRect(50, 131, 31, 20))
        self.lineEdit_number_of_scans_at_point.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_number_of_scans_at_point.setObjectName("lineEdit_number_of_scans_at_point")
        self.checkBox_is_follow_peak = QtWidgets.QCheckBox(self.groupBox_Scanning)
        self.checkBox_is_follow_peak.setGeometry(QtCore.QRect(160, 120, 81, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_is_follow_peak.sizePolicy().hasHeightForWidth())
        self.checkBox_is_follow_peak.setSizePolicy(sizePolicy)
        self.checkBox_is_follow_peak.setObjectName("checkBox_is_follow_peak")
        self.groupBox_seeking_contact = QtWidgets.QGroupBox(self.groupBox_Scanning)
        self.groupBox_seeking_contact.setEnabled(True)
        self.groupBox_seeking_contact.setGeometry(QtCore.QRect(270, 20, 191, 201))
        self.groupBox_seeking_contact.setObjectName("groupBox_seeking_contact")
        self.label_6 = QtWidgets.QLabel(self.groupBox_seeking_contact)
        self.label_6.setGeometry(QtCore.QRect(30, 10, 71, 39))
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_seeking_contact)
        self.label_7.setGeometry(QtCore.QRect(120, 10, 71, 51))
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.groupBox_seeking_contact)
        self.label_9.setGeometry(QtCore.QRect(30, 80, 141, 51))
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.lineEdit_level_to_detect_contact = QtWidgets.QLineEdit(self.groupBox_seeking_contact)
        self.lineEdit_level_to_detect_contact.setEnabled(True)
        self.lineEdit_level_to_detect_contact.setGeometry(QtCore.QRect(120, 60, 61, 20))
        self.lineEdit_level_to_detect_contact.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_level_to_detect_contact.setObjectName("lineEdit_level_to_detect_contact")
        self.lineEdit_backstep = QtWidgets.QLineEdit(self.groupBox_seeking_contact)
        self.lineEdit_backstep.setEnabled(True)
        self.lineEdit_backstep.setGeometry(QtCore.QRect(30, 60, 63, 20))
        self.lineEdit_backstep.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_backstep.setObjectName("lineEdit_backstep")
        self.lineEdit_max_allowed_shift = QtWidgets.QLineEdit(self.groupBox_seeking_contact)
        self.lineEdit_max_allowed_shift.setEnabled(True)
        self.lineEdit_max_allowed_shift.setGeometry(QtCore.QRect(120, 120, 61, 20))
        self.lineEdit_max_allowed_shift.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_max_allowed_shift.setObjectName("lineEdit_max_allowed_shift")
        self.checkBox_is_squeeze_span_for_seeking_contact = QtWidgets.QCheckBox(self.groupBox_seeking_contact)
        self.checkBox_is_squeeze_span_for_seeking_contact.setEnabled(True)
        self.checkBox_is_squeeze_span_for_seeking_contact.setGeometry(QtCore.QRect(20, 160, 161, 17))
        self.checkBox_is_squeeze_span_for_seeking_contact.setIconSize(QtCore.QSize(1, 1))
        self.checkBox_is_squeeze_span_for_seeking_contact.setShortcut("")
        self.checkBox_is_squeeze_span_for_seeking_contact.setObjectName("checkBox_is_squeeze_span_for_seeking_contact")
        self.checkBox_is_low_res_for_seeking_contact = QtWidgets.QCheckBox(self.groupBox_seeking_contact)
        self.checkBox_is_low_res_for_seeking_contact.setEnabled(True)
        self.checkBox_is_low_res_for_seeking_contact.setGeometry(QtCore.QRect(20, 180, 161, 17))
        self.checkBox_is_low_res_for_seeking_contact.setIconSize(QtCore.QSize(1, 1))
        self.checkBox_is_low_res_for_seeking_contact.setShortcut("")
        self.checkBox_is_low_res_for_seeking_contact.setObjectName("checkBox_is_low_res_for_seeking_contact")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.checkBox_is_seeking_contact.clicked['bool'].connect(self.groupBox_seeking_contact.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_Scanning.setTitle(_translate("Dialog", "Scanning parameters"))
        self.label_4.setText(_translate("Dialog", "Scanning step, um"))
        self.label_5.setText(_translate("Dialog", "Contact step, um"))
        self.lineEdit_current_file_index.setText(_translate("Dialog", "1"))
        self.label_8.setText(_translate("Dialog", "from _ "))
        self.lineEdit_seeking_step.setText(_translate("Dialog", "30"))
        self.lineEdit_scanning_step.setText(_translate("Dialog", "30"))
        self.comboBox_scanning_type.setItemText(0, _translate("Dialog", "Along Z, get contact along X"))
        self.comboBox_scanning_type.setItemText(1, _translate("Dialog", "Along Y, get contact along X"))
        self.comboBox_scanning_type.setItemText(2, _translate("Dialog", "Along Y, get contact along Z"))
        self.comboBox_scanning_type.setItemText(3, _translate("Dialog", "Along X, get contact along Z"))
        self.comboBox_scanning_type.setItemText(4, _translate("Dialog", "Along X, get contact along Y"))
        self.lineEdit_stop_file_index.setText(_translate("Dialog", "100"))
        self.label_2.setText(_translate("Dialog", "to"))
        self.checkBox_save_out_of_contact.setToolTip(_translate("Dialog", "save only difference between in_contact and out_of_contact spectra"))
        self.checkBox_save_out_of_contact.setText(_translate("Dialog", "Save out of contact"))
        self.checkBox_is_seeking_contact.setToolTip(_translate("Dialog", "Search contact at each scanning point"))
        self.checkBox_is_seeking_contact.setText(_translate("Dialog", "Seek contact"))
        self.label_3.setText(_translate("Dialog", "# sweeps"))
        self.lineEdit_number_of_scans_at_point.setText(_translate("Dialog", "1"))
        self.checkBox_is_follow_peak.setToolTip(_translate("Dialog", "Set span center to the peak position"))
        self.checkBox_is_follow_peak.setText(_translate("Dialog", "Follow peak"))
        self.groupBox_seeking_contact.setTitle(_translate("Dialog", "Seeking contact"))
        self.label_6.setText(_translate("Dialog", "Losing contact step, um"))
        self.label_7.setText(_translate("Dialog", "Level to recognize contact"))
        self.label_9.setText(_translate("Dialog", "Max. allowed shift , um"))
        self.lineEdit_level_to_detect_contact.setText(_translate("Dialog", "-35"))
        self.lineEdit_backstep.setText(_translate("Dialog", "50"))
        self.lineEdit_max_allowed_shift.setText(_translate("Dialog", "1000"))
        self.checkBox_is_squeeze_span_for_seeking_contact.setToolTip(_translate("Dialog", "Squeeze Span while search contact"))
        self.checkBox_is_squeeze_span_for_seeking_contact.setText(_translate("Dialog", "Squeeze span"))
        self.checkBox_is_low_res_for_seeking_contact.setToolTip(_translate("Dialog", "Squeeze Span while search contact"))
        self.checkBox_is_low_res_for_seeking_contact.setText(_translate("Dialog", "Use low resolution"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

